### ISSUE TITLE
The visual gaudiness of the current send and receive buttons

### ISSUE THREAD

**Issue by farrahfazirah** [AlphaWallet/alpha-wallet-ios#1034]
Sorry if the title is inappropriate as I'm not sure what to title it to bring my point across.

I strongly believe we should follow the UI provided in the Zeplin board for the send and receive buttons instead of adding shadows to the current send and receive. I believe it will look cleaner when you remove the shadows and simply change the colour to the HEX code provided in the Zeplin board.

**A visual comparison**:
<img width="354" alt="screen shot 2019-01-21 at 2 34 36 pm" src="https://user-images.githubusercontent.com/20555752/51456816-02bace00-1d8a-11e9-9cf4-c2a49770052e.png">

HEX colour of the button: #69c800
Width of button: 163dp
Height of button: 57dp

vs.

<img width="354" alt="screen shot 2019-01-21 at 2 34 56 pm" src="https://user-images.githubusercontent.com/20555752/51456997-a0160200-1d8a-11e9-8e83-9944ed897716.png">

**Comment by hboon** [comment]
For posterity:

"I think it's good though to have a visual indicator that it's not entirely flat. The problem with iOS since iOS 7 is that everything is flat and you can no longer tell which UI element is tappable. It definitely looks nicer without shadows, but remember that there was feedback that in the the previous button design that users can't tell the buttons are buttons? I can remove the shadows, but let's look into how to make them more obvious?"
