### ISSUE TITLE
Handle magic links with network specification, prevent user from importing on the wrong network

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1050]
Switch to the right network automatically when importing through MagicLink 
https://github.com/AlphaWallet/alpha-wallet-android/issues/521

**Comment by James-Sangalli** [comment]
@colourful-land this would require a change to the link format itself, by specifying the chainID.

**Comment by colourful-land** [comment]
Let's say what @James-Sangalli  asks for is done, what should happen?

Imagine this:

1. Alice is on the main chain. She has 3 ethers. She receives a magic link from Bob.
2. The link is about an asset on DAI network. It asks for 1Dai for a Dai-Kitten.
3. Alick clicks "Yes", wallet says "insufficient balance. you have 0."
4. Alice is in shock, thinking that her Ethers are gone. She goes to the main wallet interface.
5. Because the wallet is *automatically switched to* dai, the balance is 0 on main wallet interface. She confirmed that and freaks out.

Can we get @farrahfazirah's attention to work on an acceptable user flow on this and various other multi-change scenarios? The best way to move forward is to tell stories graphically. Farrah, we need to speed things up so can you produce (for design-space exploration purpose) wireframes only and not the full design, refine the detail only when the design is agreed on?

**Comment by colourful-land** [comment]
Thank you, James. How urgent it is? I will work with you to get this working.

**Comment by farrahfazirah** [comment]
![switchandhint](https://user-images.githubusercontent.com/20555752/52694590-2fd35880-2fa5-11e9-8002-9c36cc27b1f2.png)

1. Alice is on the Ethereum network
2. She receives a Magiclink from Bob asking for 1 Dai 1 Kitty
3. Alice opens the link and is prompted by a message saying that the wallet will automatically switch from Ethereum to xDai as the payment is in xDai

**If Alice has xDai**
4A. Network is switched to xDai. If Alice has xDai, it will automatically transition after 3 secs (give the user a bit more time to realise they're on xDai/see their balance) to the import/purchase page.

**If Alice has insufficient xDai**
4B. Network is switched to xDai. If Alice has insufficient xDai, it will automatically transition after 3 secs (give the user a bit more time to realise they're on xDai/see their balance) to a dialog box telling her she has insufficient balance. She confirms that she is aware of this and clicks Ok.

**Visual hints for which network user is on**
<img width="406" alt="screen shot 2019-02-13 at 3 36 00 pm" src="https://user-images.githubusercontent.com/20555752/52694842-f818e080-2fa5-11e9-8cd5-ea93afdaded7.png">
<img width="447" alt="screen shot 2019-02-13 at 3 36 07 pm" src="https://user-images.githubusercontent.com/20555752/52694843-f818e080-2fa5-11e9-8554-84785eeb82bb.png">

We could display a colour and state the network name user is on at the top left corner of the wallet page

**Comment by zhangzhongnan928** [comment]
1. "display a colour and state the network name" is a good idea.
2. Don't feel the "3 secs" is necessary, as the previous page told him
about to switch network already. The normal "import page show up from the
bottom" is fine.
3. Don't need a new "insufficient balance" page, the original "not enough
eth" page is fine.
[image: IMG_3309.PNG]

**Comment by zhangzhongnan928** [comment]
1. "display a colour and state the network name" is a good idea.
2. Don't feel the "3 secs" is necessary, as the previous page told him
about to switch network already. The normal "import page show up from the
bottom" is fine.
3. Don't need a new "insufficient balance" page, the original "not enough
eth" page is fine.

![img_3309](https://user-images.githubusercontent.com/33795543/52696845-087f8a00-2fab-11e9-9b3e-5e54acc770bf.PNG)

**Comment by hboon** [comment]
Besides the current network indicator change, can I sum it up as the only change being adding the pop up with a message to inform user that we are switching networks (screen 3)?

1. It's better to show that pop up over the screen in 5A where it's part of the import flow (partly because it's easier to implement, because we don't know where the user is at the point of import).

2. Also might be a good idea to ask the user if they want to switch network or cancel (and abort the import).

3. If possible, we should delay adding the current network indicator. There's a few more things related to it. Eg. If a user see that, does it mean they can tap on it to switch networks? I remember Weiwu said support for accessing tokens from all network would be coming this year. In that case the current network indicator will be removed anyway.

**Comment by colourful-land** [comment]
@farrahfazirah if you have an indicator on wallet screen, shouldn't you also have it on Dapp interface and on "Transaction History" interface?

@hboon  

1. Are you sure you meant that the pop up on screen 3 should be on 5A, that is, the user is asked if they want to switch chain when the chain is already switched?

2. Agreed since the user might learn that they have clicked a wrong link at that stage ("Hey I thought I am going purchase a kitten with Ether, why this link opens with such a dialogue"), they need to be able to cancel. But, I propose a more aggressive measurement. See†

3. The current network indicator will be moved to the asset instead, to mark which chain the asset is on. Of course, it will not be a switch by the latter half of the year.

@hboon @farrahfazirah -> Regarding Boon's 3rd point, the user might need to learn that the indicator is a switch, and later unlearn it when it becomes a tag by the latter half of the year. To address that, consider implementing these.

1. having a copy of the setting gear icon next to the indicator.
2. when the user touches the setting gear icon, show the chain selector as the first item in the Settings activity and mark it with the same indicator.

This way, the users will, instead of using the indicator as a switch, click the gear icon next to it.

@hboon @farrahfazirah 

† Regarding the design choices between:

A. We ask the user to switch or cancel.
B. We guide our user to the switch in "Settings" and ask the user to do the switch.

If you ask an Android designer, the balance point is B, of asking the user to do the change in settings themselves. Android users remember being asked to add permission and being brought to the permission activity to set it themselves. If you ask an iOS designer, the balance point is A. iOS users remember being asked "your item isn't in Australia Store, do you want to switch to Singapore AppStore" with a Yes/No question.

But in this case, I think the equilibrium point is on B. Reason: whoever received xDai, there is 99% chance that he will need to switch to Ethereum network back in the following weeks, since not much functions are offered on xDai network yet. We don't want to lose a user just because he imported an xDAI, therefore we must make sure they can come back to Ethereum with their own effort, even at the cost that of some xDai cart-abandonment. However, the design for this is non-trivial.

I will hear another round of advice and make the call.

**Comment by hboon** [comment]
> 1. Are you sure you meant that the pop up on screen 3 should be on 5A, that is, the user is asked if they want to switch chain when the chain is already switched?

@colourful-land yes, if we display that popup in screen 3 over 5A, we don't switch the network until the user confirms (and if we have a cancel button in that popup, tapping cancel would just close 5A too, like the existing cancel button in 5A).

> 2. * Agreed since the user might learn that they have clicked a wrong link at that stage ("Hey I thought I am going purchase a kitten with Ether, why this link opens with such a dialogue"), they need to be able to cancel. But, I propose a more aggressive measurement. See†

> †If you ask an Android designer, the balance point is B, of asking the user to do the change in settings themselves. Android users remember being asked to add permission and being brought to the permission activity to set it themselves. If you ask an iOS designer, the balance point is A. iOS users remember being asked "your item isn't in Australia Store, do you want to switch to Singapore AppStore" with a Yes/No question.

iOS uses both styles. There are examples of supporting users making the change manually in iOS too, usually after the first time the choice was made, so it makes sense too. For example for access to camera/photo libraries, the first time the app prompts for it, the users will be able enable or disable it based on the prompt provided by the system (but it appears like it is shown by the app). But if the user enables access and goes to Settings to disable it, the app can only manually inform the user to go to settings to re-enable access themselves.

> But in this case, I think the equilibrium point is on B. Reason: whoever received xDai, there is 99% chance that he will need to switch to Ethereum network back in the following weeks since not much functions are offered on xDai network yet.

>We don't want to lose a user just because he imported an xDAI, therefore we must make sure they can come back to Ethereum with their own effort, even at the cost that of some xDai cart-abandonment.

Given this priority, yes, (B) sounds better. It'd also train them to learn how to switch networks (back to Ethereum later). This is also much less and easier to implement. I suggest we add back the titles for the tab bar with this iteration. Then it'd be clearer to the user when we refer to the "Settings tab".

> 2. when the user touches the setting gear icon, show the chain selector as the first item in the Settings activity and mark it with the same indicator.

Is the current-chain indicator shown in every screen? The position in the wireframe means it's closer to where the iOS back button in the navigation bar as well as the tiny back button in the status bar (Refer to screenshot. Shown when you switch from 1 app to another, eg. tap a MagicLink in Messages.app and switch to AlphaWallet app and you should see the tiny back button to go back to Messages). If it can be tapped, that means there could be 2-3 buttons within close proximity. Or we could just make it not tappable since it's not going to be there forever.

Another thought: we can put the current chain's name on the settings tab button over the Settings icon. It'll almost always be present, and It also gives a clue where to tap to switch chains. (Technical limitation means we'd have to create several icon images with the chain name hardcoded into each image).

<img width="443" alt="screen shot 2019-02-14 at 2 34 04 pm" src="https://user-images.githubusercontent.com/56189/52767665-252cc800-3066-11e9-9a91-ff2c82c3f711.png">

**Comment by colourful-land** [comment]
@hboon said:
> Is the current-chain indicator shown in every screen?

It doesn't make sense otherwise. If you are afraid that the user will see their Ether balance disappear when they switched to xDai, you should be equally afraid that the user will login to their daily Kitty Arena DAPP and found that he has zero kitties or zero ether to buy a kitty, or that the user goes to Transaction and not seeing his Ether histories.

**Comment by colourful-land** [comment]
@farrahfazirah is tasked to produce an update that:

1. Apply the current chain indicator to every part of the wallet, including asset card, dapp, and probalby in settings too.

2. Produce "change current chain if you say Yes" and "change the current change in Settings" mock-up.

3. Please feedback on my opinion that the indicator should not be a switch but a settings button should be placed next to it for easy switching.

**Comment by zhangzhongnan928** [comment]
I provide some thoughts:
There are token issuers who have token and DApps
There are also services provider who only have DApps

If there is no DApps, then there is no trouble of switching networks, we can just put all the token from different network together with a mark of which network they are on(we already have the mark says "Ethereum network" "xDai network" )  
So the switching networks trouble are mainly for DApps, if we all the DApps live in DApp browser, then the easy solution is put a switch button and an indicator in DApp Browser.

**But our wallet support TBML which allow applets, and those applets are living in the token card.**
1. for "token issuers who have token and DApps", their Dapps live with their token, their token lives in a network, so as long as we mark clearly which network are these token on, there is no issue for the Dapps ( example Dai and xDAI, they can be 2 token cards in the same wallet page)

2. for "There are also services provider who only have DApps" these Dapps are not living with a token, 
They can run on different networks with different tokens. This is the difficult part. How to let the user chose which network to run, and how to clearly show them which network they are using. 

3. In future, the user will need to use our wallet to choose which service they want to use, then our wallet gives him a default setting(which Dapp, which layer1, which layer2), a normal user can use the default setting, an advanced user can choose their own preference. 

P.S. it seems to fail into the old discussions, a wallet should be token first or DApp first. @colourful-land 

Our current layout has a good start, as we give each token a token card, and on the card, we have marked which network are they on. I think the **first step** is to make the "mark" more clear(easy to be noticed and understand), make switch network easy and atomically. The **second step** is to "hide" the networks, all the tokens regardless network in one place.

**Comment by farrahfazirah** [comment]
The idea of having an indicator (on every screen) has been scrapped.

![switchmode](https://user-images.githubusercontent.com/20555752/52934464-79e78000-3391-11e9-92cb-fa4d74958b87.png)

1. Users can switch network from the "Wallet Title" (let's coin this the network switch).
2. Users can abort the process when they're asked to switch networks
3. After the purchase process, a tooltip appears and it tells the user on how they can switch networks. Perhaps, the tooltip should only appear once - we train the users for only the first time.
4. When user clicks on network switch, it leads to a dropdown of all the networks

**Comment by farrahfazirah** [comment]
<img width="623" alt="screen shot 2019-02-18 at 3 44 21 pm" src="https://user-images.githubusercontent.com/20555752/52935323-13179600-3394-11e9-80e2-70e63dc5cb2c.png">

As for the DApp browser, let's take a leaf out of Trust's book. I suggest we replace the home icon to the network switcher. Users can simply click on the DApp browser icon on navigations if they want to go back to the homepage.

**Comment by hboon** [comment]
> As for the DApp browser, let's take a leaf out of Trust's book. I suggest we replace the home icon to the network switcher.

@farrahfazirah if we go with this, then we can reuse the existing picker from Settings to switch when the user taps the network switcher button (screen 6 in the storyboard above) rather than show a different UI.

> Users can simply click on the DApp browser icon on navigations if they want to go back to the homepage.

Are you referring to tapping on the tab bar button to go back to Home?

**Comment by farrahfazirah** [comment]
![switch browser](https://user-images.githubusercontent.com/20555752/52969573-cc558a80-33eb-11e9-8737-3bdbb3e92d29.png)

@hboon If we are going to use the existing picker from Settings- when user clicks on back button are they led back to the browser or the main wallet page? Of course it should be led back to the browser but just wanted to mention it, in case.

> Are you referring to tapping on the tab bar button to go back to Home?

<img width="265" alt="screen shot 2019-02-19 at 2 11 18 am" src="https://user-images.githubusercontent.com/20555752/52969693-2bb39a80-33ec-11e9-87f2-c1febd96dd02.png">

I'm referring to this icon above.

**Comment by hboon** [comment]
> If we are going to use the existing picker from Settings- when user clicks on back button are they led back to the browser or the main wallet page? Of course it should be led back to the browser but just wanted to mention it, in case.

@farrahfazirah good point. We want it to stay in the browser of course. But no matter if we reuse the screen from Settings tab or a new picker screen, the app as it is rebuilds the entire UI, so the work to change it to stay on the browser needs to be done. There’s a chance it might be too difficult though so will have to try it out to see.

Yes the bar at the bottom is the tab bar. The one at the top with the back button and title is the navigation bar in iOS terms.

**Comment by farrahfazirah** [comment]
**Invision**
Switch Network Mode for Payment
https://invis.io/58QLV7F6EA2

Browser v1.1 Switch Network
https://invis.io/SCQLWQA9F27

**Zeplin**
Switch Network Mode for Payment https://app.zeplin.io/project/5b9f0106d9457b0252dbbffa/dashboard?seid=5c6d25271c25679a7c7655ea

Browser v1.1 Switch Network
https://app.zeplin.io/project/5b9f0106d9457b0252dbbffa/dashboard?seid=5c6d25271c25679a7c7655ea

The following is a summary of what the feature entails:

**Features for Switch Network Mode for Payment**
1. User is prompted by a dialog to switch network if they're not on the right network for the payment e.g. Bob sends MagicLink to Alice asking for 1 xDAI for his cryptokitties but Alice is on Ethereum network, thus she is prompted to switch to xDAI chain
- Actions users can take: continue to switch network or cancel and go back (abort import)
2. If it's user's first time switching network, a tooltip appears on how the user can switch networks
- Tooltip will disappear if user clicks onto other screens/undertakes any other action on the app, even if it's not Settings

**Features/Modification for Browser v1.1 with Switch Network**
1. Home icon has been replaced by network icons/network picker
2. User can click on the network icons to switch to a different network

**Comment by hboon** [comment]
- [ ] Switch Network Mode for Payment
- [ ] Browser v1.1 Switch Network
