### ISSUE TITLE
Deep link redirect from mobile browser to Alpha Wallet's DApp browser

### ISSUE THREAD

**Issue by Dobrokhvalov** [AlphaWallet/alpha-wallet-ios#1102]
Hey, 

is there a way to redirect users to Alpha Wallet from normal web2 browser to Alpha Wallet's DApp browser using a deep link?

**Comment by James-Sangalli** [comment]
@hboon do you think we would be able to check if alphawallet is installed and then open it up? I guess this would be dependant on the website itself?

**Comment by hboon** [comment]
> do you think we would be able to check if alphawallet is installed and then open it up? I guess this would be dependant on the website itself?

Right, the website would have to do it in this case.

In a better world, we could have proposed a standard way to do this via a custom URL scheme, say `dapp://` e.g.  `dapp://https://thedapp.com/something`, then any app can implement the `dapp://` custom URL scheme. But unfortunately, this doesn't work well in iOS because any app can claim to support any custom URL scheme and the app that gets marked by iOS as the custom URL handler isn't predictable and is not configurable by the user. (a much better iOS behaviour would have been to pop up a list of app which support the custom URL scheme and let the user choose from)

Probably the way to go is still to do a app-specific deep link like `alphawallet://https://thedapp.com/something`, but the generator of the link would have to either choose a favourite app (AlphaWallet hopefully) or present a list of links. We discussed this internally a while back and I think we should implement something like this, but we hadn't reach a conclusion if this is exactly how we would do it.

**Comment by zhangzhongnan928** [comment]
How can support the deep link to DApp browser quickly and combine it with existing MagicLink later. @colourful-land

**Comment by zhangzhongnan928** [comment]
How to "combine" DeepLink with MagicLink? @colourful-land 
- [ ] once click, jump from a link to AlphaWallet Dapp Browser, open up the Dapp, perform an action(wait for the user to confirm) (Without TokenScript)
- [ ] once click, jump from a link to AlphaWallet transaction confirming page(MagicLink importing page) (wait for the user to confirm) (With TokenScript)
- [ ] Jump between pages/actions inside AlphaWallet. eg, 1 click jump from Dai token card to cDai token card. 1 click jump from Dai token card to cDai token card and perform an action in cDai. 
- [ ] allow OS to use AlphaWallet as a web browser, eg. I can choose to use AlphaWallet DApp Browser as the default browser. I can choose to open any website in AlphaWallet.

**Comment by colourfreak** [comment]
Close this issue?

**Comment by hboon** [comment]
Yeah.
