### ISSUE TITLE
Alpha-Wallet-IOS Integration

### ISSUE THREAD

**Issue by aacostarua** [AlphaWallet/alpha-wallet-ios#1114]
Hey I recently spoke with Victor about implementing my customized wallet experience for a specific use case.  He told me to reach out to the developers/engineers to resolve this.  After forking the IOS code, I replaced xDai with all the properties of our given operating side-chain of POA.  The goal was to just show the wallet for the ERC20s on that given network.  When I sent the ERC20s,  the wallet balance never updated nor did it show on Blockscout as a wallet.  I believe there may be something missing in the Swift configuration.  The goal is also be to remove all pairs except for our POA sidechain ERC20 network and the Ethereum network,  as well as rendering the ERC721s from both.  Looking forward to working with you guys soon in the future and hope to get a decent demo up soon .  And let me know if I should add my forked code to Github to be reviewed.  Thanks.

**Comment by James-Sangalli** [comment]
@aacostarua Is my understanding correct that you are making your own POA side chain which is compatible with blockscout and you tested replacing the xdai chain node URL with your own? Is your side chain supported with blockscout? 

Regarding ERC20's, our wallet supports them fully but cannot show a balance on the users side without them either adding the token manually or having had already sent a transaction to the given contract; this happens because we are still querying nodes which cannot index for us and provide incoming transactions (since transactions of ERC20 tokens go through the contract state and not directly to the recipient), the user can still manually add the token or send a transaction to the contract and have it show up automatically. 

Feel free to share your fork with me too!

**Comment by aacostarua** [comment]
Yes exactly.  It is compatible w Blockscout as well.  And will actually be a direct cash out to USD, as well as bridge to mainnet.  Ok that makes sense on the ERC20s.  So the temporarily fix would be to have it send a default transaction upon creation of app/wallet to that contract to initialize their ERC20 wallet?  Could something like this be easily done?. And I will upload and post my fork here tomorrow.  Cheers.

**Comment by aacostarua** [comment]
Or would it still not show inbound transactions?

**Comment by aacostarua** [comment]
Heres my fork @James-Sangalli https://github.com/aacostarua/alpha-wallet-ios-paradise .  Tried using the Paradise network adding https://bc4.mycryptobox.com/tokens/0x9820cf30a77cd9e4544adfb39d0daf9e8cdd7583/token_transfers as a custom token.  Sent ERC20's to this.  It went through but didn't update the alpha wallets balance.  Not sure whats going wrong.

**Comment by James-Sangalli** [comment]
@aacostarua ouch no git history! Haha. 

Could you please try adding the token 0x6ae1896d1e3eccbaccfe85aaa5e4b9cfcde6441d manually by clicking on the plus icon in the home screen?

**Comment by aacostarua** [comment]
I tried that.  Thanks

**Comment by aacostarua** [comment]
I tried adding the ERC20 token contract manually using : 0x9820cf30a77cd9e4544adfb39d0daf9e8cdd7583, it recognized it and loaded.  But tokens never showed in the wallet just 0 Paradise. Even when I successfully transferred tokens to it.  I tried adding 0x6ae1896d1e3eccbaccfe85aaa5e4b9cfcde6441d , this was a wallet address I believe, said it was unverified as well.  Not sure what to try next.  Thanks.

**Comment by aacostarua** [comment]
Also even attempted to replace mainnet information with my network.  Still doesn't work with that setup.  Wondering what I should I try next? @James-Sangalli

**Comment by James-Sangalli** [comment]
Please paste the contract source code

**Comment by aacostarua** [comment]
Why do you need my contract source code?  Its a standard ERC20.  The query's aren't working to Blockscout I believe.

**Comment by James-Sangalli** [comment]
Because I need to ensure it fits the standard spec, if the node is working and the contract is discoverable it should be easily able to get your balance. Could you please show me the diffs you made with the original source so I can make sure all the changes you made are ok? (would be best to fork the project with git history and add the changes, that way you can track it properly)

**Comment by aacostarua** [comment]
I cant send the ether on my network to the wallet either.  So I don't believe it has to do with the ERC20 contract.

**Comment by aacostarua** [comment]
Also this network works with a trust IOS wallet, token & ether balances are updated.  Must be my config.  And I know this is a fork.

**Comment by James-Sangalli** [comment]
@aacostarua please show me the diff so I can see what you changed, your fork wasn't forked (the history was deleted)

**Comment by aacostarua** [comment]
Invited you to the repo called paradise-alpha-wallet-ios.  Tracked my edits this time.  It renders the balance of the ERC20 (after manually adding the contract), but it says unverified and doesn't allow sending to any address.  Nor is it showing any transactions of any sort.

**Comment by James-Sangalli** [comment]
Handled outside.
