### ISSUE TITLE
Simulator's search bar in dapp browser will only let you type something once

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1228]
Then it becomes impossible to use again.

**Comment by hboon** [comment]
@James-Sangalli have you toggled the software keyboard to off? If you did, try enabling it (Hardware > Keyboard > Toggle Software Keyboard (cmd+k). You might have to do this in another text field since there's something wrong with the search bar in the dapp browser. I think this implies it doesn't work correctly with external (i.e. hardware keyboards) and hence why it works on a device and not iOS.

Still good to fix it for users who use external keyboards.

**Comment by James-Sangalli** [comment]
https://stackoverflow.com/questions/56284673/cannot-type-in-emulator-search-bar

**Comment by hboon** [comment]
Might be a bug in our code
