### ISSUE TITLE
Apple pay doesn't work in AlphaWallet DAppBrowser

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1321]
https://buy.carbon.money/
![A276529B-5CBD-4F0E-A9A1-E496250A55BC](https://user-images.githubusercontent.com/33795543/61772034-9f8f1e80-ae34-11e9-898d-7a76ad5b0ca1.png)

**Comment by hboon** [comment]
There isn’t a way to support Apple Pay in the app browser without changing the dapp itself to make it very awkward because:

There are 3 ways to provide a web view in apps. (A) UIWebView, (B) WKWebView and (C) SFSafariViewController.

(A) Old. Replaced by (B)
(B) We use this.
(C) The most secure, but it’s a full screen window. The one that the Twitter app uses is SFSafariViewController (at least it looks like that). But there’s little things we can do with it other than opening a URL. We can’t inject web3js. So we can’t use (C)

Apple only supports Apple Pay with websites for (C) and their mobile Safari app [1].

[1] "In iOS, Apple Pay is supported in Safari and in SFSafariViewController objects." https://developer.apple.com/documentation/apple_pay_on_the_web
