### ISSUE TITLE
Extract function: data[64] += 27

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1369]
Extract function: data[64] += 27

https://github.com/AlphaWallet/alpha-wallet-ios/blob/master/AlphaWallet/KeyManagement/EtherKeystore.swift#L438

This same code appears a few times and I want to make sure it's more intention revealing and easier to find if we ever need to tweak it by extracting it into a 1-line function. @colourful-land can you help suggest a name for the function or variable?

(This looks like the v of (r, s, v))

**Comment by colourful-land** [comment]
This piece of code looks wrong to me. Why is 𝑣 a constant (27)?

the signing code EthereumSigner should be fixed to generate the correct 𝑣 value because this value couldn't be calculated from the outside. But what you can do is to try one by one. there are 4 possible values. The other two besides 27/28 are ignored because they only happen when the point is out of the field 𝑛 (if I remembered it correctly) which happens like less than 1/multi-million.

If this can't be fixed in EthereumSigner, we need to do 4 guesses with the correct public key in mind (get it from `EthereumAccount`?)

**Comment by hboon** [comment]
It adds 27 to `v`, not hardcodes it to 27.

**Comment by colourful-land** [comment]
> It adds 27 to `v`, not hardcodes it to 27.

Then it is correct.

**Comment by colourful-land** [comment]
I would call it Vitaliklize because he chose 27.

**Comment by hboon** [comment]
Haha! Ok. Thanks.
