### ISSUE TITLE
Only prompt user presence the first time the key is accessed during backup and verification. Prompt again if app goes to background or if user choose to go from yellow to green bar

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1393]
My wallet was not backed up yet. I have just enabled Touch ID in my phone. When I started to back up my wallet, the system asks me about Touch ID too many times. 

It asked me while:
- opening Seed Phrase to write this down
- when the system requested to verify Seed Phrase
- when I managed to enter the Seed Phrase successfuly
- when I wanted to lock my seed phrase
- when I was prompt to use Touch ID

Solution: at this stage, ask users for Touch ID only in the last step. Why do you need to touch in order to verify seed phrase for instance?

https://www.dropbox.com/s/v51bh4011mrm0qe/2019-08-27%2010.39.08.mp4?dl=0

**Comment by hboon** [comment]
The reason the user is prompted every time when the seed phrase is accessed is because the encrypted seed phrase has to retrieved and decrypted. There are a few ways to address this:

1. A) Store the seed phrase in memory across screens B) and sometimes when the app is in background. [1]
2. B) Make the seed phrase (technically the encrypted seed phrase and encryption key) available for a bit more

Both increases security risks, but is better for usability. (B) in particular might come in handy for TokenScript. We should revisit this later. So no-fix for now. @JamesSmartCell

The above applies to reading to raw private keys too.

[1] The latter is because in the screens where the user is shown the seed phrase and well as in the screen where the user verifies the seed phrase, we clear the seed phrase from the screens when the app goes to the background and prompt the user to retrieve the seed phrase when the app is active again

**Comment by colourful-land** [comment]
There are too many A B and 1 2 in the comment, not sure if I got it.

**Comment by colourful-land** [comment]
> B) sometimes when the app is in background

We don't need to save users from repeated authentications in B).

> (2) in particular might come in handy for TokenScript. 

It might. I can think of a few scenarios where it is needed. I'm not sure if the better solution (improve protocol, by using a derivated key instead of the original in the memory) is acceptable for the current market, so we may need that 2) you mentioned.
