### ISSUE TITLE
Hide "Clear" when successfully entered seed phrase

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1396]
No need for the "Clear" button when the seed phrase is entered correctly. You can accidentally misclick it, then the whole progress is gone = frustration.
When button finally becomes green, hide the "Clear"

@JamesSmartCell Please do that for Android too. 

![2019-08-27 10 23 51](https://user-images.githubusercontent.com/51817359/63743011-03d64f80-c8c5-11e9-9e64-9c5720a155dc.png)

**Comment by hboon** [comment]
Will change it so that the clear button has these states:

1. Disabled when no one is chosen
2. Enabled when user taps the first word and thereafter
3. Until user taps the 12th word and we disable it again (and we enable the Verify Seed Phrase button)

Rationale for (3) being the user likely wants to Verify now and we don't want to risk the user accidentally tapping on the clear button.

@JamesSmartCell too.
