### ISSUE TITLE
CTA button should be higher

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1398]
The bottom spacing should be around 30pt. 

This was taken on iPhone 6s. I assume it might be problematic on iPhone X where you don't have a classic Home button. 

<img width="416" alt="Screen Shot 2019-08-27 at 12 54 26 PM" src="https://user-images.githubusercontent.com/51817359/63744538-d5a73e80-c8c9-11e9-9e19-e305570cd7d5.png">

You can apply this to all screens where the button is at the bottom.

**Comment by tomekalphawallet** [comment]
Also, for not active buttons please use the color: #d7ebc8

**Comment by hboon** [comment]
> Also, for not active buttons please use the color: #d7ebc8

Moved to #1404 d7ebc8

**Comment by hboon** [comment]
>  This was taken on iPhone 6s. I assume it might be problematic on iPhone X where you don't have a classic Home button.

@tomekalphawallet are you saying to set it to 30pt for both iPhone X and non-iPhone X because it'll be a problem for iPhone X? Or to set it to 30 pt for non-iPhone X and more for iPhone X?

It's currently a thin margin for non-iPhone X and already adjusted for iPhone X (iOS has APIs for providing how much additional margin for iPhone X).

**Comment by tomekalphawallet** [comment]
I don't have iPhone X device yet. I might get iPhone 11 once this is released. Because of that, I can't see how is it displayed. 

What I know is that on non iPhoneX devices the button is too close to the bottom. It's a minor thing. It just looks odd to me.

**Comment by hboon** [comment]
Ah. That’s ok. I’ll lift it up for non-IPhone X. It’s ok for iPhone X because there’s a safe margin already.

**Comment by hboon** [comment]
They currently look like this:

before iPhone X | iPhone X and later
-|-
<img src="https://user-images.githubusercontent.com/56189/64093603-8f4f5500-cd8b-11e9-878c-ce07a76ef0d7.png" width=200> | <img src="https://user-images.githubusercontent.com/56189/64093601-8f4f5500-cd8b-11e9-80b5-3ea05d63cb9c.png" width=200>

After the change for pre-iPhone X (with 30pt margin at the bottom):

<img src="https://user-images.githubusercontent.com/56189/64093599-8eb6be80-cd8b-11e9-8411-3270a378a2db.png" width=200>

Notice that tab bars look like this:

<img src="https://user-images.githubusercontent.com/56189/64093602-8f4f5500-cd8b-11e9-95c3-fcde5563eb55.png" width=200>

The thicker margin for iPhone X is not only aesthetic, it's needed so that the user doesn't accidentally touch the home bar indicator on the screen.

@tomekalphawallet If you want to proceed with the change (30pt) or a different value, let me know?

**Comment by tomekalphawallet** [comment]
Can you try with 20pt?

**Comment by hboon** [comment]
@tomekalphawallet <img width="200" alt="Screenshot 2019-09-05 at 2 56 36 PM" src="https://user-images.githubusercontent.com/56189/64318745-63cba500-cfed-11e9-95f3-d96b0613b4c0.png">
