### ISSUE TITLE
Keep one network label in each token card.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1414]
Currently there are 2 network labels on each token card. It is a bit of wasting and confusing.

![19E5B786-FCBB-49E9-8DD5-0A418DF47F74](https://user-images.githubusercontent.com/33795543/63941384-da791780-caae-11e9-9ee4-d29926d65ed6.jpeg)

We should keep only one.

**Comment by tomekalphawallet** [comment]
@zhangzhongnan928 Finally have an allowance to do that! I can't wait to work on these cards.

**Comment by tomekalphawallet** [comment]
@zhangzhongnan928 @jzaki  This is a bold change, so I would like to hear the feedback from anyone in the team. I simplified the first tab.

<img width="841" alt="Assets:Coin" src="https://user-images.githubusercontent.com/51817359/64938019-a65f6e00-d886-11e9-8d0c-d7434f199f07.png">

- First tab is called "Assets" now
- I moved "Add Token" below
- No more heavy colors and backgrounds
- I added Coin Symbols

**Comment by hboon** [comment]
@tomekalphawallet Thanks! Much more efficient use of space in the Assets tab. Some thoughts and comments:

Assets tab
---
* Why do we call it Assets instead of Wallet? (because we use Wallet numerous times in the Settings tab)
* What is the difference between All and Currencies? (we currently have All, Currency and Assets)
* Do we show a placeholder icon when we don't have a logo for a row? Will it be likely that most of them don't have an icon? Where do we get icons?
* For tokens that aren't native crypto currency, e.g. FIFA, do we no longer show which network they are on? Some cases where it might be confusing: CryptoKitties are on both Ethereum mainnet and Rinkeby. In the current design, the pill-shaped labels with filled background were supposed to invoke user-familiarity through the colors the users are supposedly (already?) familiar with.
* What happens when the user scroll to reveal the rows at the bottom. Do the header (showing the total value) scroll off the top? Would be good if it does
* We no longer show value appreciated. I don't know if it is useful to have
* What is the "Jun 13th" for the FIFA ticket row? (If it is the date of the match, the token can represent one or more tickets from one or matches, so that wouldn't work, and it's specific to FIFA tickets, so we'll need to handle when it's not available, i.e. 99% of the tokens)
* Most if not all tokens that are not native crypto currency, e.g FIFA, will not have a fiat value
* The thin border around the token icons looks a bit unfinished

Send/Receive screen
---
* Assuming this is for native crypto currency and ERC20s
* How are TokenScript action buttons shown?
* Is it showing 3 transaction records or as many as we can?
* What happens when the user scroll to reveal the rows at the bottom. Do the header (showing the total value) scroll off the top? Would be good if it does
* Maybe it's intentional (dynamics?) the oval in the Receive and Send buttons aren't symmetrical. Have you experimented with a version that is more circular? Wonder how it would look like? (and maybe we can remove the gray circular background in transactions if the symbols are already circular?)
* I know most wallets have some form of receive and send buttons and often use arrows as symbols. But here's one thought, how about using a QR code icon as the receive button. That's what it does, right?
* Why do we switch the positions of Send and Receive buttons (left/right)?
* Shall we show the full address in the transactions history and only truncating if we can't fit them in small screens? (maybe we still need to truncate for the biggest screen, but we can show more)
* Similar to the Assets tab, we probably still need to show the network name
* In the current iOS version (when we tap on "Ethereum Blockchain" it opens Etherscan/blockscout. Would still be good to have that for power users (and developers like us).
* How is TokenScript signature verification status and express of trust shown?
* Since we already used the same icons for Send and Receive buttons above, I wonder if we can remove the text "Sent" and "Received" from the transaction history? But maybe it'll be inconsistent with the Transaction tab?
* We used to have green numbers for amount received and red to denote amount sent. That seemed to be rather good for scanning. Alternatively considering making the Sent icon in the transaction list red?

**Comment by tomekalphawallet** [comment]
### Assets tab

> Why do we call it Assets instead of Wallet? (because we use Wallet numerous times in the Settings tab)

This is realated to @jzaki comment about the Wallet tab. https://docs.google.com/drawings/d/1zVEYOD-ukvUote5k1Uo-jC6aASXz3IvQTA_qRfaudz4/edit
This is the context for a wallet app, not one quarter of it

> What is the difference between All and Currencies? (we currently have All, Currency and Assets)

We can adapt these tabs to anything we want. I am open to suggestions.

>Do we show a placeholder icon when we don't have a logo for a row? Will it be likely that most of them don't have an icon? Where do we get icons?

I can provide icons. We can create own base. 

> For tokens that aren't native crypto currency, e.g. FIFA, do we no longer show which network they are on? Some cases where it might be confusing: CryptoKitties are on both Ethereum mainnet and Rinkeby. In the current design, the pill-shaped labels with filled background were supposed to invoke user-familiarity through the colors the users are supposedly (already?) familiar with.

We have a second row (light grey color) to display secondary informations. The goal is to declutter cards. Is it possible to have a kitty that look exactly the same (the thumbnail) but is on different networks? 

> What happens when the user scroll to reveal the rows at the bottom. Do the header (showing the total value) scroll off the top? Would be good if it does

Yes, you are correct. Only tabs are sticked to the top. 

> We no longer show value appreciated. I don't know if it is useful to have

I believe it's not. As long as we do not offer trading. 

> What is the "Jun 13th" for the FIFA ticket row? (If it is the date of the match, the token can represent one or more tickets from one or matches, so that wouldn't work, and it's specific to FIFA tickets, so we'll need to handle when it's not available, i.e. 99% of the tokens

I asked in the group if someone can send me screenshots. I received the wallet address to watch, that was ... empty. So I used what previous designer did. If you could send me examples of other tokens, it would be great!

> Most if not all tokens that are not native crypto currency, e.g FIFA, will not have a fiat value

Then, instead of saying $19.223 USD we can say 19.223 ETH. If you tap on it, you can switch to USD (according to current market price). I believe this is an excited information to all speculators. You basically please your ego looking on how wealthy you are. 

> The thin border around the token icons looks a bit unfinished

Not sure why you think so?

**Comment by tomekalphawallet** [comment]
### Send/Receive screen

> Assuming this is for native crypto currency and ERC20s

Yes

> How are TokenScript action buttons shown?

What do you mean by Tokenscript action buttons? If you would like to display more than just 2 (Send, Receive) buttons on the screen, you can easily do that. 3 buttons can easily fit, if you want more, swipe left to see more (you will a half of button no.4 to indicates there are more after swipe)

> Is it showing 3 transaction records or as many as we can?

These 2 screens are just 2 out of 30+ screens are made. The reason why I asked for a feedback is that they are really important for the whole flow (and for the entire app) If I won't get this approved, then I have to tweak the rest too (to look like the same app). 

I am still working on this part, but you can see what I have already came up with here: 
https://www.dropbox.com/s/1n6wazkfcb9tr3b/Ethereum_Coin.png?dl=0

> What happens when the user scroll to reveal the rows at the bottom. Do the header (showing the total value) scroll off the top? Would be good if it does

Yep.

> Maybe it's intentional (dynamics?) the oval in the Receive and Send buttons aren't symmetrical. Have you experimented with a version that is more circular? Wonder how it would look like? (and maybe we can remove the gray circular background in transactions if the symbols are already circular?)

This is still pending. I am working on it. 

> I know most wallets have some form of receive and send buttons and often use arrows as symbols. But here's one thought, how about using a QR code icon as the receive button. That's what it does, right?

Then the symbol of "Received" should be a QR code too. Which is not ideal. As mentioned, would be happy to get a feedback on icons too. Keep in mind that we would need a.Sent b. Received c. Rejected d. Failed e. Purchased and probably many more.

> Why do we switch the positions of Send and Receive buttons (left/right)?

Otherwise it would looked like these two arrows have a beef. Makes more sense to me to be honest.
 
> Shall we show the full address in the transactions history and only truncating if we can't fit them in small screens? (maybe we still need to truncate for the biggest screen, but we can show more)
Similar to the Assets tab, we probably still need to show the network name

No need for a full address. I believe these addresses are scary. Do you recognize which one is yours by looking at the middle numbers? Most of the time last 4-5 or the first 4-5.

> In the current iOS version (when we tap on "Ethereum Blockchain" it opens Etherscan/blockscout. Would still be good to have that for power users (and developers like us).

Do you know if any of our users do use this option? I would track this first, then decide if it's worth keeping it or not.  Is this important for you as a developer? How important?

> How is TokenScript signature verification status and express of trust shown?

Not sure what do you refer to.

> Since we already used the same icons for Send and Receive buttons above, I wonder if we can remove the text "Sent" and "Received" from the transaction history? But maybe it'll be inconsistent with the Transaction tab?

I believe that one day you could use just a ENS of the sender/recipient. But this is still melody of the future. 

> We used to have green numbers for amount received and red to denote amount sent. That seemed to be rather good for scanning. Alternatively considering making the Sent icon in the transaction list red?

This is tricky. We had that at the beginning. But the red color is associated with a failure/error. And receiving any funds is always a good emotion (as long this is not a reimbursement for a funeral costs etc.)

**Comment by hboon** [comment]
Assets tab
---

> > Why do we call it Assets instead of Wallet? (because we use Wallet numerous times in the Settings tab)

> This is the context for a wallet app, not one quarter of it

Ok. Assets is certainly more correct, but Wallet is more common. Anyway, not a big deal.

> > Do we show a placeholder icon when we don't have a logo for a row? Will it be likely that most of them don't have an icon? Where do we get icons?
> 
> I can provide icons. We can create own base.

We can create our own icons for the native crypto currency rows. There are 11 of them for now. But almost every other token will not have an icon, because while there are popular ones like CryptoKitties, tokens are really like user-generated-content here — there can be an infinite number of them created by someone, somewhere. Do we use a single placeholder icon for them? i.e when we scroll a list of 100 tokens, other than the 11 native crypto currency icons which are unique, the other 89 of them are the same placeholder icon (if that's what we are thinking of doing).

> > For tokens that aren't native crypto currency, e.g. FIFA, do we no longer show which network they are on? Some cases where it might be confusing: CryptoKitties are on both Ethereum mainnet and Rinkeby. In the current design, the pill-shaped labels with filled background were supposed to invoke user-familiarity through the colors the users are supposedly (already?) familiar with.
> 
> We have a second row (light grey color) to display secondary informations. The goal is to declutter cards. Is it possible to have a kitty that look exactly the same (the thumbnail) but is on different networks?

Related to the point above about placeholder icons. Also, a row here represents a token (so "CryptoKitties" not "CryptoKitties #1 whose name is Kitty"), so the icon will probably be quite generic. Or it could be a generic CryptoKitties icon with a badge like "Ethereum" over it, but then that's back to displaying it.

> I asked in the group if someone can send me screenshots. I received the wallet address to watch, that was ... empty. So I used what previous designer did. If you could send me examples of other tokens, it would be great!

I think the wallet was James'. Maybe you have to enable the Rinkeby network.

> > Most if not all tokens that are not native crypto currency, e.g FIFA, will not have a fiat value
> 
> Then, instead of saying $19.223 USD we can say 19.223 ETH. If you tap on it, you can switch to USD (according to current market price). I believe this is an excited information to all speculators. You basically please your ego looking on how wealthy you are.

Those tokens wouldn't have an ETH value too (sorry, should have noticed that earlier)

> > The thin border around the token icons looks a bit unfinished
> 
> Not sure why you think so?

Just an impression

**Comment by hboon** [comment]
Send/Receive screen
---

> > Assuming this is for native crypto currency and ERC20s
> 
> Yes
> 
> > How are TokenScript action buttons shown?
> 
> What do you mean by Tokenscript action buttons? If you would like to display more than just 2 (Send, Receive) buttons on the screen, you can easily do that. 3 buttons can easily fit, if you want more, swipe left to see more (you will a half of button no.4 to indicates there are more after swipe)

The 3 buttons (Enable, etc) to the left of the Send button are added via TokenScript. We don't have a limit for the number of buttons that can be added (yet). But shrinking the button label font size to fit them as we do now is just a stop-gap measure. One way I suppose is to set a maximum of 2 additional buttons and if there are more, hide it become some kind of "..."/more construct.

<img width="200" src="https://user-images.githubusercontent.com/56189/65023978-88693a80-d966-11e9-88cc-b2934348e23a.png">

> > Is it showing 3 transaction records or as many as we can?
> 
> These 2 screens are just 2 out of 30+ screens are made. The reason why I asked for a feedback is that they are really important for the whole flow (and for the entire app) If I won't get this approved, then I have to tweak the rest too (to look like the same app).

I don't understand. The current design for this screen shows exactly 3 (or fewer if the wallet has fewer transactions), whereas there is a separate Transaction tab which shows as many transactions are we can.

I am asking if in this new design, is it still showing 3 transactions or is the entire list scrollable in this screen? This is relevant also because in the current design, the transaction date is shown for each record, but in the new design, it's shown as a header which hints that there are more (all?) records that can be revealed when you scroll. This is also relevant because if this screen shows all the transactions, then maybe we don't need the Transactions tab anymore.

Did I misunderstand your request for comment? I can limit my comments to just the visual design and exclude the architecture and UX, if you'd prefer to look at them separately.

> > I know most wallets have some form of receive and send buttons and often use arrows as symbols. But here's one thought, how about using a QR code icon as the receive button. That's what it does, right?
> 
> Then the symbol of "Received" should be a QR code too. Which is not ideal.

Not necessarily. We can look at the Receive button (as part of Send and Receive) as a way to get the address, and not actually to receive a transaction. Seen that way, they don't have to have the same representation. In fact, the "Receive" button could well be accessible from the Assets tab, at the top left or right corner as a QR code icon or "Receive" button. It's all the same Ethereum address for every native crypto currency and native token until we support chains other than Ethereum. Users *might* have been used to finding Send and Receive buttons together though, but moving it out makes it much more convenient.

> > Shall we show the full address in the transactions history and only truncating if we can't fit them in small screens? (maybe we still need to truncate for the biggest screen, but we can show more)
> > Similar to the Assets tab, we probably still need to show the network name
> 
> No need for a full address. I believe these addresses are scary. Do you recognize which one is yours by looking at the middle numbers? Most of the time last 4-5 or the first 4-5.

I'm referring to the address at the other side of the transaction though. It's often not my wallet address. If I send from my wallet A to B, B is the address shown here. So I don't have to remember them. If I want to look up a transaction, it could be useful.

> > In the current iOS version (when we tap on "Ethereum Blockchain" it opens Etherscan/blockscout. Would still be good to have that for power users (and developers like us).
> 
> Do you know if any of our users do use this option? I would track this first, then decide if it's worth keeping it or not. Is this important for you as a developer? How important?

It's very important as a developer, because it lets you verify the transaction yourself. I know Victor uses it too. I have no idea if other use it too. But we can just let the icon take its place though.

> > How is TokenScript signature verification status and express of trust shown?
> 
> Not sure what do you refer to.

In the screenshot above, there's a green tick and green text "Verified by aw.app". That's the signature verification status. We might have display express of trust too.

> > Since we already used the same icons for Send and Receive buttons above, I wonder if we can remove the text "Sent" and "Received" from the transaction history? But maybe it'll be inconsistent with the Transaction tab?
> 
> I believe that one day you could use just a ENS of the sender/recipient. But this is still melody of the future.

I meant, since the user is trained to recognise the send and receive icons, the icons and the words "Sent" and "Receive" repeats itself for each row representing a transaction.

> > We used to have green numbers for amount received and red to denote amount sent. That seemed to be rather good for scanning. Alternatively considering making the Sent icon in the transaction list red?
> 
> This is tricky. We had that at the beginning. But the red color is associated with a failure/error. And receiving any funds is always a good emotion (as long this is not a reimbursement for a funeral costs etc.)

Yes, hence:

Received (good!) = Green
Sent (no good) = Red

> But the red color is associated with a failure/error. 

Are you saying that users are complaining this is misleading?

**Comment by jzaki** [comment]
I wont add too much to this since I've already given a wave of feedback earlier, but one thing I'd like to note is that it will become exceedingly difficult to be both a tool for developers as well as an intuitive/simple mobile wallet for users.

QR code for receive implies prior knowledge, if we are sure our users will know/remember this, then we might go that path, but alternately, QR codes are going to be used in other areas (eg idea around QR code to read passphrase?)

I think I had pointed out the red tx colour concern (#ParkinsonsLawOfTriviality) but I defer to Tomek's experience on this domain, in combination with outcomes from user research towards product requirements (eg feeling confident with use), and also comparable product features (eg bank statements).

**Comment by jzaki** [comment]
And the multiple assets across multiple networks should be considered an edge case as it is not recommended (see related ticket and validation). But how to address this might have to be addressed at another stage so as to not add to this initial UI upgrade.

**Comment by tomekalphawallet** [comment]
@hboon You are more than welcome to join our design-sync meetups. I prefer to talk, writing here slows me down a lot. And keep me away from what I am working on. 

Do you see any positives from the new look? Can you please point them out too? So far, only constraints.

**Comment by hboon** [comment]
> @hboon You are more than welcome to join our design-sync meetups. I prefer to talk, writing here slows me down a lot. And keep me away from what I am working on.

@tomekalphawallet yes, I have been thinking of joining a couple of times, but can't make it daily. Asynchronous communication works much better for me, but I sent feedback here because you requested here.. Would you buzz me when there's a suitable session and send a meetup link when you like feedback like this?

> Do you see any positives from the new look? Can you please point them out too? So far, only constraints.

Sorry. I took it for granted that no comment means they are good :) My bad.

But first of all, I don't mean the feedback as just constraints or complaints :) Most of it are meant to be taken as "have you considered..." or "how about..", though maybe I can phrase all of them differently.

Anyway, here's what is good:

1. Much more efficient use of space for content in rows
2. Better use of colors. "Buttons" are tinted with a single color which is no longer used for background
3. More obvious "Add token" button (I wonder if it's better to just be a + icon, removing the circle). Another way is to integrate "Add Token" into search. We have a search bar at the top
4. Removing the duplicate network names are good (but like I pointed out earlier, not sure if some kind of indicator should remain)

On the whole, there are improvements in terms of visual design and representation, but interactions remain the same (and maybe that's the point?)

Another suggestion responding to James' comment about tabs. What if we change the All, Currencies and Collectibles from the current form into the use of segmented control (for iOS), which is more familiar for iOS users. The original design seemed to take inspiration from Android's tabs which isn't native in iOS.

Responding to a comment (somewhere) about removing the tab bar: I don't think there's a good idea. Because phones tend to be longer nowadays, tab bars at the bottom is (A) efficient use of vertical space (B) within reach with single hand use (C) and very familiar for users. I feel tabs are ugly, but it's what works and where other apps are going..

**Comment by hboon** [comment]
Another suggestion: Show the address or whichever name/icon indicates which wallet is currently active in the Assets tab?

**Comment by tomekalphawallet** [comment]
> Do we show a placeholder icon when we don't have a logo for a row? Will it be likely that most of them don't have an icon? Where do we get icons?
> 
> I can provide icons. We can create own base.
> 
> We can create our own icons for the native crypto currency rows. There are 11 of them for now. But almost every other token will not have an icon, because while there are popular ones like CryptoKitties, tokens are really like user-generated-content here — there can be an infinite number of them created by someone, somewhere. Do we use a single placeholder icon for them? i.e when we scroll a list of 100 tokens, other than the 11 native crypto currency icons which are unique, the other 89 of them are the same placeholder icon (if that's what we are thinking of doing).

We can make up 10 placeholders at the beginning. But then, we would need to follow numbers. To explain, if from the analytical tool (which we don’t have now) we will learn that they use one “category” more than other, then we can make an icon. Worst scenario is if we make 100 icons from scratch. Because we might never use them. So I suggest to start with 11 currencies + 10 placeholders (ticket, retail, sport, etc.) Kind of like categories. 

> The 3 buttons (Enable, etc) to the left of the Send button are added via TokenScript. We don't have a limit for the number of buttons that can be added (yet). But shrinking the button label font size to fit them as we do now is just a stop-gap measure. One way I suppose is to set a maximum of 2 additional buttons and if there are more, hide it become some kind of "..."/more construct.

What about something like this?
![2019-09-18 08 52 19](https://user-images.githubusercontent.com/51817359/65127988-c88df300-da22-11e9-8e34-2e03608e3236.png)

> Is it showing 3 transaction records or as many as we can?
> 
> These 2 screens are just 2 out of 30+ screens are made. The reason why I asked for a feedback is that they are really important for the whole flow (and for the entire app) If I won't get this approved, then I have to tweak the rest too (to look like the same app).
> 
> I don't understand. The current design for this screen shows exactly 3 (or fewer if the wallet has fewer transactions), whereas there is a separate Transaction tab which shows as many transactions are we can.
> 
> I am asking if in this new design, is it still showing 3 transactions or is the entire list scrollable in this screen? This is relevant also because in the current design, the transaction date is shown for each record, but in the new design, it's shown as a header which hints that there are more (all?) records that can be revealed when you scroll. This is also relevant because if this screen shows all the transactions, then maybe we don't need the Transactions tab anymore.
> 
> Did I misunderstand your request for comment? I can limit my comments to just the visual design and exclude the architecture and UX, if you'd prefer to look at them separately.

Transaction tab is needed. You can see all Transactions on Ethereum if you open Ethereum, then all transactions from all coins within Transaction tab. If we would have deleted the Transaction tab, it could be problematic to search for a specific transaction. For example... 2 months ago you bought a ticket (you are not sure which chain it was or anything). How would you go and find it out? 

Also, if the transaction has failed and you won't see a notification (local or push), we can also have a small red circle with "1" inside to indicate there is something to check out. Without the tab, you would be able to do this. Also, we can keep "send" and "receive" buttons at the top of Transaction tab. Then, next step you have to select the coin. Coinbase Wallet does the same. 

> I know most wallets have some form of receive and send buttons and often use arrows as symbols. But here's one thought, how about using a QR code icon as the receive button. That's what it does, right?
> 
> Then the symbol of "Received" should be a QR code too. Which is not ideal.
> 
> Not necessarily. We can look at the Receive button (as part of Send and Receive) as a way to get the address, and not actually to receive a transaction. Seen that way, they don't have to have the same representation. In fact, the "Receive" button could well be accessible from the Assets tab, at the top left or right corner as a QR code icon or "Receive" button. It's all the same Ethereum address for every native crypto currency and native token until we support chains other than Ethereum. Users might have been used to finding Send and Receive buttons together though, but moving it out makes it much more convenient.

FYI, I have updated the look (icons). Arrow up = send, arrow down = receive. Green = success, red = failure, gray = pending
https://www.dropbox.com/s/zk9242ipbsb69a2/Ethereum_Coin.png?dl=0

> In the current iOS version (when we tap on "Ethereum Blockchain" it opens Etherscan/blockscout. Would still be good to have that for power users (and developers like us).
> 
> Do you know if any of our users do use this option? I would track this first, then decide if it's worth keeping it or not. Is this important for you as a developer? How important?
> 
> It's very important as a developer, because it lets you verify the transaction yourself. I know Victor uses it too. I have no idea if other use it too. But we can just let the icon take its place though.

I can find a room for that in the Transaction Details screen. 

> Do you see any positives from the new look? Can you please point them out too? So far, only constraints.
> 
> Sorry. I took it for granted that no comment means they are good :) My bad.
> 
> But first of all, I don't mean the feedback as just constraints or complaints :) Most of it are meant to be taken as "have you considered..." or "how about..", though maybe I can phrase all of them differently.

Ok, cool. If you really want to do something, you’ll find a way. If you don’t, you’ll find a constraint (excuse). So let's try to find a way.

If you want to help, please provide me screenshots of any token you have (could be a kitty, Fifa ticket, land on the Moon). Anything that has an interface and I don't have an access too. 

Thanks!

**Comment by zhangzhongnan928** [comment]
Watch my wallet address, I basically have all type of tokens.
0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63

Do you think customised tab is a good idea,
1. maybe allow users to customise these tabs (name, position, what tokens are included, add new tab)
2. provide some default tabs for different personas  



		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by colourful-land** [comment]
Closing this issue because it's no longer executable.
