### ISSUE TITLE
Only accept ERC721 from OpenSea

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1427]
Discovered when DAI card was suddenly supported by OpenSea

**Comment by hboon** [comment]
Renamed this issue and create a new issue based on the original title at #1428

**Comment by hboon** [comment]
OpenSea has now included DAI (ERC20) in their results (maybe more) to their versioned endpoint (v1) and providing an additional `"schema_name"` field with the values `"ERC20"` and `"ERC721"` (maybe more that we have not observed). We only process the values with `"ERC721"` with this issue to be safe.

**Comment by hboon** [comment]
If we want to use the non-ERC721 token information returned from OpenSea, there's a bigger change involved because our codebase isn't expecting non-ERC721 tokens. eg. after we pull results from OpenSea, we iterate through the list of ERC721 tokens in our local database and pick out those that aren't in OpenSea and refresh them outside of the OpenSea call. We'll have to do this for ERC20 tokens too.

There might be more of such cases.
