### ISSUE TITLE
Some transaction cannot adjust gas price

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1478]
Like MagicLink, NFT transfer and most of the TokenScript transections.

Should we use the same transection page for all the transections.

**Comment by hboon** [comment]
There’s an action sheet-based UI that Weiwu and Tomek are working that standardise this.

**Comment by jzaki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[__] As a user, I want understanding/control over transaction processing time, so that I can transact with confidence](https://trello.com/c/26MTjbSU/70-as-a-user-i-want-understanding-control-over-transaction-processing-time-so-that-i-can-transact-with-confidence)
