### ISSUE TITLE
EIP681 links

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1533]
https://brunobar79.github.io/eip681-link-generator/#

currently, click link it will open up BDR.
Make it open up AlphaWallet

**Comment by hboon** [comment]
@zhangzhongnan928 AlphaWallet is already marked as supporting `ethereum:` for native crypto (Ether) transfers [1]. This is an iOS limitation and wouldn't work for us.

If you delete BDR and tap the link again, AlphaWallet might open. Or you might need to delete a few other wallet apps before AlphaWallet takes over.

This is because on iOS, any app can state that they support a particular custom URL scheme (i.e `ethereum:` or `awallet:`, anything that isn't standard like `http(s):` or `tel:`, etc). iOS picks 1 app — maybe it's the first app or the last app installed, or maybe it's random — and treats that app as the handler.

Unfortunately, this affects the system camera too. i.e. if you scan a QR code with a `ethereum:` link, it will have the same problem.

Scanning QR code with `ethereum:` works in the AlphaWallet app itself because the app decides what to do with it.

A good reason for https://trello.com/c/c8KiXWgv/96-as-a-merchant-i-want-users-to-be-able-to-scan-payment-qr-codes-encoding-eip-681-for-native-and-token-transfers-more-easily

[1] But we haven't added support for ERC 20 transfers #1526

**Comment by hboon** [comment]
Closed for reasons ^
