### ISSUE TITLE
Decimal point doesn't work in spanish

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1599]
Maybe because it uses a comma instead

**Comment by hboon** [comment]
@James-Sangalli can you elaborate how and where it doesn't work?

**Comment by James-Sangalli** [comment]
My bad, go to the app, change it to spanish and then go to make a transfer. Try to use the decimal point there and it won't work

**Comment by hboon** [comment]
I can reproduce it in the simulator if I change the locale for iOS, but not if I switch in-app. We are currently parsing it based on the user locale, so "1.1" is invalid.

Seems like expected behavior? (though the ether amount displayed in the confirmation screen should be consistent, it's displayed as "-1.1" instead of "-1,1")

What would you like it to do instead?

**Comment by James-Sangalli** [comment]
@hboon on my device I cannot input a decimal place at all, it should be allowed or should switch the decimal for a comma on the input pad
