### ISSUE TITLE
TokenScript client displays values as NaN after opening and closing views a few times again

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1652]
Similar to #1530 ? Tapping around, opening and closing Dai related TokenScript views for ~30 sec according to Victor's video.

**Comment by hboon** [comment]
A hunch. Maybe Infura throttling.

**Comment by James-Sangalli** [comment]
@hboon can't reproduce this

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 are you still able to reproduce this?

**Comment by zhangzhongnan928** [comment]
I saw there are several PRs related to this same issue, but it is never solved.
Lucky that we don't have anyone really using TokenScript enable tokens(besides me doing some demos), otherwise, I'm 100% sure we will receive compliant every day. 
**Is there a way, at least I can manually refresh those attributes?**
**Can we confirm whether it is the issue from infura or our wallet?**
(It works sometimes, normally after restarting the app, and I tested it with my home wifi, office wifi and mobile 4g. so it is definitely not an internet issue.)

Not working in Victor928.eth
https://share.icloud.com/photos/0UPXD28CIPWR7BCdS1tlMEnQw

Not working in zxcvb.eth
https://share.icloud.com/photos/0hiMWzDkcUPtSq03we3MTeDeA

From working to not working in both Victor928.eth and zxcvb.eth
https://share.icloud.com/photos/0DsF34B6xtVIVO4bsGDuz7qWA

**Comment by hboon** [comment]
@zhangzhongnan928 Let's try to narrow it down.

When you see the N/A problem, visit http://hboon.com/w.html in the dapp browser (with mainnet) in the same device and see if the balance is displayed. It uses the same Infura URL and key and displays the cZRX balance.

**Comment by hboon** [comment]
Just realised I hardcoded it to a specific wallet address. But shouldn't doesn't matter.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 Let's try to narrow it down.
> 
> When you see the N/A problem, visit http://hboon.com/w.html in the dapp browser (with mainnet) in the same device and see if the balance is displayed. It uses the same Infura URL and key and displays the cZRX balance.

![IMG_4143](https://user-images.githubusercontent.com/33795543/89264399-2ac10800-d676-11ea-8ed3-67132b3d8ed3.PNG)
![IMG_4142](https://user-images.githubusercontent.com/33795543/89264408-2eed2580-d676-11ea-9be2-e88ff19ec869.PNG)

**Comment by zhangzhongnan928** [comment]
> Just realised I hardcoded it to a specific wallet address. But shouldn't matter.

I have tried to break the http://hboon.com/w.html, but it always displays the balance, never shows NaN

**Comment by hboon** [comment]
> I have tried to break the http://hboon.com/w.html, but it always displays the balance, never shows NaN

 At least rules out Infura. Should be a bug in the TokenScript engine. Will fix it.

**Comment by zhangzhongnan928** [comment]
@hboon any updates on this bug?

**Comment by hboon** [comment]
@zhangzhongnan928 not yet, after I get a part of Activities (but disabled) in first because this affects a lot of code. The order is like this:

1. Get a part of Activities. But still disabled. — almost there
2. Look into this bug — can't fix this immediately because it affects a lot of the code that Activities touches
3. Resume Activities

**Comment by zhangzhongnan928** [comment]
Still has the same issue in build 3.06(352)

**Comment by hboon** [comment]
@zhangzhongnan928 does it get stuck with NaN like it used to after it's triggered? Or is it something different, eg. 1 off problem, try again and it might work (or it might not)?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 does it get stuck with NaN like it used to after it's triggered? Or is it something different, eg. 1 off problem, try again and it might work (or it might not)?

It works with first few actions, then start showing nan for following actions(including the ones work before). Then after I typed above words in GitHub, go back to app. It works with first few actions, then ......... repeat this behaviour.
