### ISSUE TITLE
Update Settings Tab Icons [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1659]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/p/settings
https://sketch.cloud/s/e4OJW/v/m1G19z/a/kZ3Km9/r/DP2LVa
https://sketch.cloud/s/e4OJW/v/m1G19z/a/lJ3RD4
https://sketch.cloud/s/e4OJW/v/m1G19z/a/Rr7ynx
https://sketch.cloud/s/e4OJW/v/m1G19z/a/qO3bk2/r/DP2LVa
https://sketch.cloud/s/e4OJW/v/m1G19z/a/7Kj1OP/r/DP2LVa

Zeplin:
- https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5dfc1f63646faf970d746224
- zpl://project?seid=5dfc1f63646faf970d746224&pid=5d0356be2f25b319dcc5944b
- https://zpl.io/VYn67Bw
- https://zpl.io/2ZB67gG
- https://zpl.io/bee6jYz
- https://zpl.io/bee6kjp

There are three types of components

- 60pt high with an icon
- 80pt high with an icon and secondary line
- 60pt high with an icon and toggle

Additional screens
- Advanced and Support will open another screen
- Advanced 
- Support 
- Modals (Back up my wallet, lock phrase)

**Comment by tomekalphawallet** [comment]
![settings_icons](https://user-images.githubusercontent.com/51817359/72553873-df8e0600-3899-11ea-93a9-0ffeb09f1e5c.png)
![settings_modals](https://user-images.githubusercontent.com/51817359/72553899-f2a0d600-3899-11ea-978e-9b25d25a968f.png)

**Comment by hboon** [comment]
Not specific to this issue (ed: will probably move this somewhere else)
---
* We currently build with Xcode 10.1. We are halfway through upgrading the project file to Xcode 11.x
* Keep commits atomic and commit messages clear
* Rebase upstream/master when there are changes in master

You can check the font and colors used in Zeplin and access them in code, e.g.

* SourceSansPro-Bold — Use `Fonts.bold(size: X)`
* azure — Normally use `Colors.appTint` or other variables in `Colors` if appropriate. In rare cases, access `R.colors.X()` directly if it makes sense to

**Comment by hboon** [comment]
@nimitparekh2020 for this issue, would you focus on the list (the rows) like the one seen in the  screenshot on the left and keep the various header (which says "Lock your seed phrase") in the screenshot on the right unchanged?

There might be a few rows which exist only in Zeplin and not in the app. For those cases, just stick to those that are in the app and can you list out those that are found in Zeplin, but not in the app? Vice versa, if we need additional icons which don't exist in Zeplin.

Can you also see if you can do this just using UITableView directly, without using Eureka as it is now. Create a new class `SettingsViewController2` for now. So we can keep `SettingsViewController` and all the classes it uses around until we finalise this

- [ ] Use UITableView directly instead of Eureka
- [ ] Rows
- [ ] Make sure that Headers like "Lock your seed phrase" still shows up correctly. You can force it to appear by creating a new wallet. It should show a red header with "Your Wallet is not backed up!".

Don't do this yet:

- [ ] Headers like "Lock your seed phrase"
- [ ] Remove the old SettingsViewController and related classes

|In scope|Ignore for the time being|
-|-
<img width="250" src="https://user-images.githubusercontent.com/56189/78100332-12668580-7417-11ea-8a59-97d581f2d493.png">|<img width="250" src="https://user-images.githubusercontent.com/56189/78100348-21e5ce80-7417-11ea-9924-930a32f4b8c4.png">

**Comment by hboon** [comment]
Closed by #1871
