### ISSUE TITLE
Update My Wallet Address screen [Fiji]

### ISSUE THREAD

**Issue by tomekalphawallet** [AlphaWallet/alpha-wallet-ios#1664]
Sketch Cloud:
https://sketch.cloud/s/e4OJW/v/DP2LVa/a/pG3YlG

Zeplin:
https://zpl.io/bPnwYYp

- ~~Add Smart QR Code Scanner icon in the top right to quickly switch to camera~~ (edit: mentioned in #1214. The functionality of an all-purpose camera hasn't been built yet, but it'll be really useful in several places, and we'll then be able to add it to the iOS quick actions list, as well as use it in several places within the app)
- clicking "tomek.eth" copies to clipboard
- display ENS + address below

**Comment by tomekalphawallet** [comment]
![my_wallet_address](https://user-images.githubusercontent.com/51817359/72555585-23363f00-389d-11ea-99f5-c8d2ea16c04f.png)

**Comment by hboon** [comment]
> Add Smart QR Code Scanner icon in the top right to quickly switch to camera

@tomekalphawallet 

1. What does scanning QR code do?

2. We currently show the balance (ETH and USD, the latter if appropriate) instead of "My Wallet Address". You don't want that anymore?

**Comment by hboon** [comment]
@tomekalphawallet the Ethereum address is quite a bit longer than in the design so the fonts have to be quite small to display the full address. Doesn't look so nice.

It doesn't feel like we can replace it with ellipsis, because it might be the one place the user can verify the full address. If we do, maybe the user can tap on it to expand in the label, at the cost of usability. 

What do you think?

WIP Screenshot on the iPhone X (which has one of the widest screens):

<img src="https://user-images.githubusercontent.com/56189/73324249-53121900-4285-11ea-9b34-9cd99d402631.png" width=200>
