### ISSUE TITLE
Actionsheet-style confirmation for "normal" transactions

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1689]
i.e. not TokenScript and not MagicLink(s)

**Comment by hboon** [comment]
To replace this screen as well as the screen shown when the gear button is tapped. This is for ERC20s and Native crypto (i.e. Ether and xDai)

<img src="https://user-images.githubusercontent.com/56189/87016095-d9516480-c200-11ea-9284-fb494875ec4c.PNG" width=200>

To look like this:

When confirm is tapped — and because the app is going to sign the transaction — we prompt for Face ID / Touch ID (the existing code should prompt for it automatically as long as you try to post the transaction like we did before this PR)

While waiting, as the "progress bar", we show: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e26d519966e017e134e9051 (don't worry about the fields in this Zeplin page)

When transaction is posted: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e9984c8a6aa117d06166efe (don't worry about the fields in this Zeplin page).

Use your discretion to put every field in the current screen into the actionsheet. Look in Zeplin, under the "ActionSheets" section to get a feel how it should work.

Just make Speed (Gas) a hardcoded row for now. But we'll need to implement it in this PR.

Ignore things like "Assets", "Address", etc in Zeplin.

Bear in mind that the fields (cells) aren't static. It's a fixed set for this PR, but in separate PRs, we'll need to be able to configure them at runtime.

We'll have to work out some of the details of how it works as we go along.

I have some WIP in this branch https://github.com/AlphaWallet/alpha-wallet-ios/tree/activity, but it was meant for TokenScript transactions, not ERC20/native crypto. But you can see if you want to copy over the WIP UI or rebuild it.

**Comment by vladyslav-iosdev** [comment]
@hboon i updated Confirm PaymentView Controller with tableView, that now allows show/hide sections content, and ability to resize view controller. if i understood right i need devide existed content with these sections. What rows i need display in "Speed (Gas)" section?
<img width="207" alt="Screenshot 2020-07-10 at 12 00 39" src="https://user-images.githubusercontent.com/55975226/87137229-3e5e9600-c2a5-11ea-81dd-bc72b925b0f2.png">

**Comment by vladyslav-iosdev** [comment]
not it looks like this
<img width="467" alt="Screenshot 2020-07-10 at 12 21 43" src="https://user-images.githubusercontent.com/55975226/87138986-ef663000-c2a7-11ea-90b4-2a634775a171.png">

**Comment by hboon** [comment]
@vladyslav-iosdev in Zeplin, there should be a screen where it shows how gas can now be configured with normal/faster (can’t remember the exact names) buttons.

The chevron arrow buttons should point right when the row is collapsed and point down when expanded.

**Comment by tomekalphawallet** [comment]
Send ETH A3 flow updated:
https://drive.google.com/file/d/10qK-VysWYLgux0iXccOihuSIk4euNDyA/view?usp=sharing

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e2ac0cdc4fc3356a32e1542

Comments:
1. Make sure that we have a back button instead of Cancel (and the transaction goes from left to right = not sliding from the bottom)
We need All Funds button where you can clear out your wallet (total-fee)
<img width="495" alt="Screenshot 2020-08-20 at 09 48 19" src="https://user-images.githubusercontent.com/51817359/90731924-a05de280-e2ca-11ea-97b6-8e904f068913.png">
2. We have the "Edit" button that takes to another screen where you have preselected speeds
Online Recipient is expandable as you need to see what is the full address.
<img width="439" alt="Screenshot 2020-08-20 at 09 48 23" src="https://user-images.githubusercontent.com/51817359/90732174-00548900-e2cb-11ea-91b4-480c2de164e2.png">
3. This screen should appear along with every transaction
<img width="597" alt="Screenshot 2020-08-20 at 09 48 37" src="https://user-images.githubusercontent.com/51817359/90732289-2c700a00-e2cb-11ea-93fc-939247059abf.png">
4. We need a pending transaction to be described in present continuous tense. Also, we need an animated spinner to indicate the transaction is pending. https://zpl.io/bzmrPgl
<img width="677" alt="Screenshot 2020-08-20 at 09 48 41" src="https://user-images.githubusercontent.com/51817359/90732620-a7d1bb80-e2cb-11ea-9a98-fcebb39c2b46.png">
<img width="539" alt="Screenshot 2020-08-20 at 09 48 48" src="https://user-images.githubusercontent.com/51817359/90732638-abfdd900-e2cb-11ea-82b3-9964a07ce1f1.png">

**Comment by vladyslav-iosdev** [comment]
@hboon can u please check #2105? there was a lot of work to be done. i would like to know if i did it right.

**Comment by AW-STJ** [comment]
Also, can we make sure that we add this event to mixpanel?

**Comment by hboon** [comment]
@AW-STJ Regarding event tracking, we have to be concise and purposeful on what we want to track. For this particular one, how about we track 2 events:

A. When this action sheet shows up (so only native crypto and ERC20, I think, transfers)
B. When the user confirms (doesn't matter if success or not)

**Comment by AW-STJ** [comment]
Sounds good Boon... let us implement those two events for this feature.

**Comment by colourfreak** [comment]
Updated a3
https://drive.google.com/file/d/13IkzRDFKmAggE3HnNILOu-v_ar-iLPB_/view?usp=sharing
