### ISSUE TITLE
need a <speed up pending transaction> function

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1809]
one transaction sends with lower gas will block all the other transaction.
speed up pending transaction function can be quite useful: resend the same transaction with same Nonce but higher gas.

![IMG_2925 2](https://user-images.githubusercontent.com/33795543/82404892-c4c8d980-9aa5-11ea-81e4-c6745e0292f3.PNG)
![IMG_2924](https://user-images.githubusercontent.com/33795543/82404899-c8f4f700-9aa5-11ea-8b06-2820c1adc64f.PNG)

**Comment by hboon** [comment]
Needs some scoping and planning. Copying this:

> 3 specific features come to mind — A) cancel a pending transaction, B) replace a pending transaction C) create a transaction with more parameters to tweak, specifically, setting nonce.
> So yes, I think it's useful :) But I have no idea how useful it is for users.

from: https://trello.com/c/26MTjbSU/70-as-a-user-i-want-understanding-control-over-transaction-processing-time-so-that-i-can-transact-with-confidence#comment-5e4b537e3e7da720b5a87d85

Sounds like @zhangzhongnan928 is suggesting B. But A and C (set nonce explicitly) is related.

**Comment by zhangzhongnan928** [comment]
> Needs some scoping and planning. Copying this:
> 
> > 3 specific features come to mind — A) cancel a pending transaction, B) replace a pending transaction C) create a transaction with more parameters to tweak, specifically, setting nonce.
> > So yes, I think it's useful :) But I have no idea how useful it is for users.
> 
> from: https://trello.com/c/26MTjbSU/70-as-a-user-i-want-understanding-control-over-transaction-processing-time-so-that-i-can-transact-with-confidence#comment-5e4b537e3e7da720b5a87d85
> 
> Sounds like @zhangzhongnan928 is suggesting B. But A and C (set nonce explicitly) is related.

A B C are same t

**Comment by hboon** [comment]
> A B C are same

@zhangzhongnan928 I was thinking of specific UI for the users rather than an advanced screen with many knobs, so in that sense technically similar underneath. But quite different from the UI:

A) cancel a pending transaction — a button "cancel" on a pending transaction
B) replace a pending transaction — a button called "speed up" and let the user enter a new gas value (or equivalent, like a slider or fast/faster/fastest)
C) create a transaction with more parameters to tweak, specifically, setting nonce. — A simpler version might be like B, but with a single textbox to set nonce

**Comment by zhangzhongnan928** [comment]
I accidentally click the comment
