### ISSUE TITLE
Upgrade dependencies to work with xcode 11.7

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#1831]
Reported from the AlphaWallet group 

Shubham Rathi, [25.05.20 20:00]
[ Photo ]
This is the issue from Macaw.

Shubham Rathi, [25.05.20 20:01]
Overriding generic methods isn't allowed (from 11.5 i suppose)

Shubham Rathi, [25.05.20 20:02]
https://forums.swift.org/t/method-override-with-a-generic-signature-with-requirements-not-imposed-by-the-base-method/33593

**Comment by hboon** [comment]
The latest version of Xcode 11.x

**Comment by vladyslav-iosdev** [comment]
@hboon i sent PR with updates to AlphaWallet/Macaw but not sure if i did it right.

**Comment by vladyslav-iosdev** [comment]
Because `exyte/Macaw` contains +82 commits i dont know how to squash them into single commit, (because of conflicts)

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli when you will have time please provide more detailed information, what need to do for this issue. For now not  clear.

**Comment by hboon** [comment]
@vladyslav-iosdev We currently only support building the repo with Xcode 11.3. We would like it to be with `11.4` (actually let's do `11.6` instead of `11.4`). What's the minimum change that we can do to support this?

We have a fork of Macaw at https://github.com/AlphaWallet/Macaw/tree/alphawallet (the alphawallet branch). Is the soltion as simple as this? :

1. Add a single commit to our Macaw fork, the alphawallet branch
2. Update `Podfile` to use that new commit

**Comment by hboon** [comment]
@vladyslav-iosdev can you try to make it build with Xcode 11.7 instead?

Refer to #2135 too

**Comment by hboon** [comment]
Also relevant: #1872

**Comment by vladyslav-iosdev** [comment]
@hboon seems like done.
