### ISSUE TITLE
Allow contract ref to take an attribute

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-ios#2038]
aDAI requires that the address be sourced dynamically via an attribute which is then used as a contract ref in a transaction. We must allow this.

**Comment by hboon** [comment]
Since it's necessary, can we allow this with our usual string interpolation syntax to catch the train and figure out if we should and/or how to bring this into TokenScript properly later?

```
          <ethereum:call function="foo" contract="${thatContract}" as="uint">
```

**Comment by James-Sangalli** [comment]
> Since it's necessary, can we allow this with our usual string interpolation syntax to catch the train and figure out if we should and/or how to bring this into TokenScript properly later?
> 
> ```
>           <ethereum:call function="foo" contract="${thatContract}" as="uint">
> ```

FYI @colourful-land

**Comment by James-Sangalli** [comment]
@hboon @colourful-land we might be able to use the hardcoded address defined here: https://etherscan.io/address/0x24a42fD28C976A61Df5D00D0599C34c4f90748c8

I will get back about this later.

**Comment by James-Sangalli** [comment]
Slashed as we can hardcode it without issue. Furthermore, because TokenScripts can be updated in realtime, it is easy for us to do manually.

**Comment by hboon** [comment]
Great. It'll work for this demo, but..

> ..because TokenScripts can be updated in realtime, it is easy for us to do manually.

@James-Sangalli do you mean this generally? For the train, we can't update after we ship it though, since it's shipped with the app.

Also I thought of an example where this can't be updated in realtime in the general case too: we compute the recipient address for our Express of Trust design. I don't know how common this is and if this ever makes sense in a TokenScript file..
