### ISSUE TITLE
Review and confirm the gas price estimation source

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2242]
The gas prices are similar for Android and iOS. 

However differ to https://ethgasstation.info/, which was recommended by Victor some time ago.

Creating this ticket to confirm the source of truth for gas estimate and then take a decision on implementation.

**Comment by hboon** [comment]
Would work on this sometime after actionsheet for transaction confirmation because the original actionsheet design includes a fast/average/slow/custom speed gas options. Current implementation in #2105 is scoped down to only offer default/custom. So would be good to either check if the current source provides this or switch to ethgasstation.info (or similar).
