### ISSUE TITLE
Face ID doesn't show up after the transaction confirmation popup with the error message 'cancelled'.

### ISSUE THREAD

**Issue by maxweng** [AlphaWallet/alpha-wallet-ios#2284]
### The issue:

When interacting with DApps, the Face ID doesn't show up after the transaction confirmation popup with the error message 'cancelled'.

### Environment
Device: iPhone 11 Pro Max
OS version: iOS 14.2

**Comment by hboon** [comment]
@maxweng which version of the app is this against?

**Comment by colourful-land** [comment]
> @maxweng which version of the app is this against?

4 days ago his original issue title was "Sending transactions failed in DApp browser after upgrading to new version". Our last release was 3.08 (Nov 3, 2020). Because Apple only allows users to upgrade to the latest version, I'm pretty sure it is 3.08 that he was talking about. @maxweng ?

**Comment by maxweng** [comment]
@colourful-land Yes, that's correct.

**Comment by hboon** [comment]
@maxweng, sorry for the late reply, it is because we have been working on an app update revamping the screens for transaction confirmation. It streamlines the operation with an actionsheet-style UI so now all kinds of transactions (native/ERC20 sends, dapps, etc) goes through the same flow, and with better gas options.

It's now live on the app store. Would you help to give it a go and see if it addresses your problem?

**Comment by maxweng** [comment]
@hboon I checked the latest code from the master branch, compiled it, and running it on my phone now. Seems all looking good. Thanks for the updates!

**Comment by hboon** [comment]
👍
