### ISSUE TITLE
The Transaction speed is delayed causing users confirming high cost of gas

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2430]
We have 1 to few seconds delay when displaying a high gas fee warning. I think would need a skeleton design animation, as it's better to do not display anything than misleading users with the wrong data. 

In the video below, it takes 7 seconds to update the gas fee. 

https://user-images.githubusercontent.com/51817359/103520305-3c9e1580-4e77-11eb-93c5-89624b0ac507.MP4

**Comment by hboon** [comment]
There are 2 screens involved here, the actionsheet as well as the custom gas screen.

@colourfreak rather than a skeleton/placeholder, do you think some way to indicate a price refresh [1] [2] would be better? There are at least 2 reasons:

A. We don't do it now, but I hope to revisit both screens and refresh the gas price (and thus gas values) in both screens at intervals. This is useful for when the user is in either screen for a long enough time for the gas prices to be outdated
B. A also opens up the possibility of tracking the recent gas price and using it until it's refreshed again so the transaction can be completed sooner and less wait for the user. This might be useful e.g when the user tries to cancel/speed up transactions

Showing a gas price in the actionsheet and then displaying a different one immediately in the custom gas screen should be considered a bug (it'll pop up eif we do a refresh, skeleton screen or not). If we can have some indicate that the price has changed, the fix can then be:

1. show the same price in the custom gas screen as it was shown in the actionsheet (this has to be done regardless of whether we introduce skeleton screens)
2. ignore taps on the Confirm button in the actionsheet after the price has changed, for say 0.1 sec. Just for the user to pick up the refreshed price

[1] and perhaps generally any sensitive value changes, but seems like price in the actionsheet and custom gas screen is where it's most applicable now.
[2] referring some kind of effect that achieves this: https://signalvnoise.com/archives/000558.php. But with a more appropriate design of course.

**Comment by colourfreak** [comment]
Looking at how this is implemented in Android - it works super fast. @JamesSmartCell How did you achieve this?

https://user-images.githubusercontent.com/51817359/104214923-625b8980-5438-11eb-8f6c-28893ca8f895.mp4
