### ISSUE TITLE
Support of ERC 1155 Tokens

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#2750]
**Invision clickable prototype:**
https://invis.io/HD10WWZ5JXA5

Zeplin:
**Project**
All ERC1155 tokens are distributed to 'Projects'. They have tabs (Info, Activity, Assets). In the Assets tap, you will find more granular division.
- https://zpl.io/2v3EQXj
----

**Single Tokens and List**
Each token differs with Details. They are: 
Issuer, Circulating Supply, Total Supply, Reserve Value, Type, Transferability, Melt Fee, Transfer Fee, Token ID, Created, Rarity, Item Type, Holders, Melts, Transfers, Description
- https://zpl.io/2ZM6ddJ

----
**Send Multiple Tokens**
- https://zpl.io/a8n5d36

**Comment by hboon** [comment]
@colourfreak @JamesSmartCell There's a technical limitation with how ERC1155 contracts work. So, the idea is ERC1155 contracts can hold more than 1 collection, e.g "Mathilde Cretier Arworks", "The Vault" and "Lost Relics") in the same contract. They can, but the contract doesn't provide a way for wallets to tell them a part. i.e. we can only know that the "Enjin" contract holds X tokens, but can't break them down into those 3 collections. Some ERC1155 contracts might be written to hold just 1 collection and in those cases, they will look better.

That means while the UI flow is the same, the data grouping will look different like this:

1. Wallet tab display 1 row per ERC1155 contract (this means "Mathilde Cretier Artworks", "The Vault" and "Lost Relics" would be shown as a single row "Enjin" instead of 3 rows with meaningful names). On the other hand tokens from this collection https://opensea.io/collection/gensys-x would show up as 1 row in the Wallet tab too. But it has a more meaning name ("GenSys.X") because the contract only manages this 1 collection
2. Tap on a row in Wallet tab (eg. "Enjin")
3. Under Assets, it will show all the _id/token IDs under this contract. For "Enjin", it will show the tokens from "Mathilde Cretier" as well as "The Vault" and "Lost Relics". If we had tapped on "GenSys.X" in the Wallet tab (which is another ERC1155 contract), the "Assets" tab will show a list of tokens from this contract.

@colourfreak let me know if this makes sense to you? I'm checking with the ERC1155 folks to be sure, but I think this is pretty much it.

**Comment by colourfreak** [comment]
Ok, noted. It makes sense.

**Comment by hboon** [comment]
@vladyslav-iosdev if you have the bandwidth, can you help build the UI? Stub out the models. You can use ERC721 tokens if it's easier. I'll figure out the backend to fetch and store the tokens.

**Comment by vladyslav-iosdev** [comment]
@hboon btw, are we going to use the same instance of `TokenObject` for `ERC 1155 Tokens`, with updating it, or its going to be something else?
do we need to user existing `TokenViewController` class or its going to be some other class?

**Comment by hboon** [comment]
@vladyslav-iosdev We can probably modify `SingleChainTokenCoordinator.showTokenList(for:token:navigationController:)` to special case for ERC1155 and launch the new UI there.

**Comment by vladyslav-iosdev** [comment]
ok, np

**Comment by vladyslav-iosdev** [comment]
@hboon where can we get these values? 
<img width="632" alt="Screenshot 2021-09-02 at 15 30 19" src="https://user-images.githubusercontent.com/55975226/131844625-19c9dbdc-0083-4b43-9161-eec7557064ab.png">

**Comment by hboon** [comment]
@vladyslav-iosdev not sure. Put some place holders and add a comment to the issue/PR so I  can fill them in later?

**Comment by colourfreak** [comment]
You can open ERC1155 tokens in Enjin to see them. I think @JamesSmartCell dealt with this already.

**Comment by hboon** [comment]
@colourfreak yes, but he’s working in the UI without the data yet :)

**Comment by hboon** [comment]
Re-opening. Still working on backend and integrating with UI

**Comment by hboon** [comment]
Done
