### ISSUE TITLE
Prompt and collect user emails

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2807]
We should collect and maintain a list of users' email. This will help us immensely in announcing new features, doing usability testing etc.

To implement after the design is confirmed. Starting the task with Tomek to confirm the interaction design.

https://github.com/AlphaWallet/alpha-wallet-android/issues/1866

**Comment by hboon** [comment]
One consideration might be how to make user not feel the email they enter is linked to their wallet activities, especially their wallet addresses.

**Comment by hboon** [comment]
@colourfreak here's how it looks like in raw form. We only need a textfield.

<img width="510" alt="Screenshot 2021-06-30 at 1 33 05 PM" src="https://user-images.githubusercontent.com/56189/123915258-e4be1280-d9b2-11eb-86a4-72c48d8e22d1.png">

**Comment by colourfreak** [comment]
![Email_Request_2](https://user-images.githubusercontent.com/51817359/132548061-dd7165d5-888d-4ad0-91a0-767513a27fd8.jpg)
![Email_Request_3](https://user-images.githubusercontent.com/51817359/132548068-756d112a-0f92-40ed-bd64-e0d058e84660.jpg)

Which one do you like more?

**Comment by hboon** [comment]
The 2nd. The graphic doesn't seem to be useful for this case. But the "We do not spam" message seems helpful. Not a strong opinion on either though. Up to you.

**Comment by colourfreak** [comment]
There is something about this "We do not spam". Some people might not even think about "They might spam me" but we are raising up this issue and pay their attention to that matter. Better if we add "One email per week"

**Comment by colourfreak** [comment]
![Email_Request](https://user-images.githubusercontent.com/51817359/132690823-f02a7a13-6b75-4701-a910-04005b2e5f1e.png)

**Comment by colourfreak** [comment]
https://zpl.io/bPNXpWm

**Comment by hboon** [comment]
Sure. Makes sense too

**Comment by colourfreak** [comment]
@hboon How do you think this is built (the animation)? Is this Swift UI? Let's say I would provide what I want this to look and feel (the transition & and very simple animation). Then what? 

What about Android?

https://user-images.githubusercontent.com/51817359/132691278-09719f2b-f5ff-49e8-81ae-2dfef7352960.mp4

**Comment by hboon** [comment]
We can’t tell definitively if something is built in SwiftUI. And we aren’t using SwiftUI. We are using Swift. We can’t use it (SwiftUI is a UI toolkit) yet because we are supporting older versions of iOS plus it wasn’t around back then when the app was first created.

Animations, generally, if the parameters are available, are easier to reproduce (there are other possible ways too like providing it in After Effect exports etc). But for now, just best to approximate it. More important things to deal with first :) 

Ditto for Android.

**Comment by hboon** [comment]
Approximate — a little vague there. But does it give you a sense of what you can provide, other than the static file(a) and sample animation?

**Comment by colourfreak** [comment]
I am curious about the bridge between what the designer provides and how this is implemented later. With static images, you can do this via Zeplin. But I wonder what is the end-file format a developer is looking for?

**Comment by hboon** [comment]
Created #3180 as follow up

**Comment by hboon** [comment]
> I am curious about the bridge between what the designer provides and how this is implemented later. With static images, you can do this via Zeplin. But I wonder what is the end-file format a developer is looking for?

Ideally, we'll want something like either #3180 for animations that don't affect the UI. The trick is when the animations affect the UI. There are some tools that let designers/programmers build the animation and then export out the animation code to be tweaked and included in the app, but it's not as clear cut as #3180, but it is necessary because it is no longer standalone.

Does that answer the question?

**Comment by hboon** [comment]
@vladyslav-iosdev would you help with this? Based  on:

* https://github.com/AlphaWallet/alpha-wallet-ios/issues/2807#issuecomment-916071725
* https://github.com/AlphaWallet/alpha-wallet-ios/issues/2807#issuecomment-916073506

Look for `EmailList.subscribe(email:)`
