### ISSUE TITLE
ERC 721 on BSC Not detected on iOS

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#2972]
A user has sent an NFT from TrustWallet to AlphaWallet and its not detected on iOS

![IMG_20210716_151959_127.jpg](https://user-images.githubusercontent.com/84448420/125946344-5a172ca9-fd1d-422a-8a03-df68eba28cd3.jpg)

The user is using Iphone XR. I get the same result on my Iphone 6e.

Android is able to detect it with watch wallet.

![Screenshot_20210716-141010_AlphaWallet~2.jpg](https://user-images.githubusercontent.com/84448420/125946575-96c8c422-18c2-4193-8bd8-f750ae2d9140.jpg)

The nft contract is 
![QR-code-of-the-contract.PNG](https://user-images.githubusercontent.com/84448420/125946617-33b86fb4-661c-4eb7-ba0f-870d5212f175.PNG)

User wallet address: 0x640a5B4e6E9A3853783601d0AFa4Cdd2AC13F6Bc

The NFT is shown in the wallet on BSCscan.

**Comment by hboon** [comment]
Expecting the next update on the app store to fix this — v3.25. Planning to submit a hotfix today so it should be out today/tomorrow.

If the user still don't see it with that new update (because of caching), add it manually with:

* Add / Hide Tokens
* +
* Paste the token contract (0xa609c3b719dcf43df52afe4e7f4b90e1dda1823e)

**Comment by hboon** [comment]
@hieronymus4826 approved. Usually available in app store within 1-2 hours

**Comment by hboon** [comment]
Would you help close the issue once you are done with it?

**Comment by hieronymus4826** [comment]
Thank you, @hboon ! I will close it once it has been tested and confirmed by the user.
