### ISSUE TITLE
Refactor so `AddRPCServerViewController.validateInputs()` is shared for both adding and editing custom chains

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3452]

**Comment by eviltofu** [comment]
The validation method is already extracted out to `EditCustomRpcViewModel.validate(...)`. Would it be better to refactor `EditRpcServerCoordinator` , `EditRpcServerViewController`, and `EditCustomRpcViewModel` to `SaveCustomRpcServerCoordinator`, `SaveCustomRpcServerViewController`, and `SaveCustomRpcViewModel` and introduce two options `add` and `edit` in the constructor of the Coordinator? Then both `AddRPCServerXXX` and `EditRpcServerXXX` classes can be replaced by one set of classes instead of two.

**Comment by hboon** [comment]
@eviltofu sounds like it could work too, yes.

BTW, there is this maybe unorthodox-looking extension inner class trick we are experimenting with. Look for an example in:

```
//Experimental. Having some of the logic in barely-functional style. Most importantly, immutable. Static functions in an inner class enforce that state of value-type arguments are not modified, but it's still possible to modify reference-typed arguments. For now, avoid those. Inner class is required instead of a `fileprivate` class because one of the value they provide is being easier to test, so they must be accessible from the testsuite
extension AddCustomChain.functional {
```

Lowercase "functional". Basically immutable functions are placed in there. The compiler can't check, but we shouldn't modify the args of reference types (classes) too.

Look for ".functional {" for more examples.

So you might look out for suitable to write in this style too.
