### ISSUE TITLE
Make tests pass on iOS 15 simulator

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3456]
Seems to be `QRCodeValueParserTests.swift` (strange!) and maybe `EtherKeystoreTests.swift`.

Follow up:

- [ ] Make travis use iOS 15 instead of 14.x

**Comment by eviltofu** [comment]
Does this include the AlphaWalletUI tests which fail with `“Cannot test target “AlphaWalletUITests” on “iPhone 12”: UITargetAppPath should be provided`?

**Comment by hboon** [comment]
No, ignore `AlphaWalletUITests`. I haven't used it in ages and don't think that work at all.

**Comment by hboon** [comment]
Remember to `.travis.yml`. That one.

**Comment by eviltofu** [comment]
The tests were failing to complete because `LockEnterPasscodeCoordinator` in `LockEnterPasscodeCoordinatorTest` did not have a corresponding `.stop` after `.start`. After fixing this issue, the unit tests were able to run again but one test `QRCodeValueParserTests` sometimes failed due to a time out. 

I noticed that the following files had no tests. Should they be removed?

- EnterSellTokensCardPriceQuantityViewControllerTests
- ImportTokenViewControllerTests
- SmartContractHelperTests
- TransactionCoordinatorTests
- TransferTokensCardQuantitySelectionViewControllerTests

Also, the AlphaWalletUITests should be removed if they don't work.

**Comment by hboon** [comment]
> After fixing this issue, the unit tests were able to run again but one test QRCodeValueParserTests sometimes failed due to a time out.

Push a PR?

> I noticed that the following files had no tests. Should they be removed?

Keep them there for now since they are disabled because they weren't working for some reason. You can try to fix it separately if you know what they are about. But very low priority.

> Also, the AlphaWalletUITests should be removed if they don't work.

Sure. Separate PR, as usual/

**Comment by eviltofu** [comment]
> > After fixing this issue, the unit tests were able to run again but one test QRCodeValueParserTests sometimes failed due to a time out.
> 
> Create a PR?
> 
It seems that it is not `QRCodeValueParserTests` but another test which uses networking which is causing the problem.
