### ISSUE TITLE
Primary/secondary/Ellipsis button colors when pressed and held down

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3946]
While we are at it, do we want to set a "selected" foreground and background color which is used when the primary and secondary buttons are held down? Apparently there's one for the secondary button already (probably provided by OS), but not for the primary button. Let's do it for both, deliberately, for dark theme too, i.e. 4 combinations:

1. primary foreground + background color for light theme
2. secondary foreground + background color for light theme
3. primary foreground + background color for dark theme
4. secondary foreground + background color for dark theme

<img width="375" alt="Screenshot 2022-02-17 at 11 07 36 AM" src="https://user-images.githubusercontent.com/56189/154397757-6176d318-9dd8-4f74-b5af-8b19db6a383b.png">

**Comment by colourfreak** [comment]
Primary Pressed
https://zpl.io/3Xk5qzx

Secondary Pressed
https://zpl.io/vMg9YyJ

Dots Pressed
https://zpl.io/6Nk8vDg

**Comment by eviltofu** [comment]
@hboon I think the Ellipse button colours might not be configured correctly. Below is the image of the button in the highlighted state. Do I make the corrections here or in another PR?

![Simulator Screen Shot - iPhone 11 - 2022-04-02 at 08 55 26 copy](https://user-images.githubusercontent.com/1050309/161357878-e78bb749-46ed-4d60-b3cd-e0d9e6bb9733.png)

**Comment by hboon** [comment]
> @hboon I think the Ellipse button colours might not be configured correctly. Below is the image of the button in the highlighted state. Do I make the corrections here or in another PR?

Same PR. Separate commit if you think it's more appropriate?

**Comment by eviltofu** [comment]
@hboon 

The [PR](https://github.com/AlphaWallet/alpha-wallet-ios/pull/4213) has the updated ellipses button. 

Currently we are using a pdf to display the ellipses "…". This is a problem because if we change the background colour for the various states, we would need to create new pdfs of the ellipse. I'm not sure if we can have a pdf with a transparent background. @colourfreak ? I corrected the code to use `setImage` and tried with transparent PNGs from Zeppelin but got the following:
![Simulator Screen Shot - iPhone 11 - 2022-04-03 at 10 38 38 copy](https://user-images.githubusercontent.com/1050309/161413325-9448fa13-0d66-47c2-8e0f-5d0be1b81730.png)

I have switched to using text to render the ellipses. 
```swift
            view.childView.setTitle("…", for: .normal)
            adjustButtonEdgeInsets(button: view.childView)
```
Since the base line of the button title is not centred, I have to manually adjust the inset to make it centred. I'm not sure if this is the best solution.

The  button.titleEdgeInsets have been depreciated since iOS 15. I've tried to use the new `configuration` variable but since we didn't use button.configuration at all, it's `nil` and the code won't affect the offset. The following code won't work at all under iOS 15:
```swift
    private func adjustButtonEdgeInsets(button: UIButton) {
        if #available(iOS 15, *) {
            if var configuration = button.configuration {
                var insets = configuration.contentInsets
                insets.bottom += 12
                configuration.contentInsets = insets
                button.configuration = configuration
            }
        } else {
            var titleEdgeInsets = button.titleEdgeInsets
            titleEdgeInsets.bottom += 12
            button.titleEdgeInsets = titleEdgeInsets
        }
    }
```
So I took the `if #available` condition code for iOS 15 out.

**Comment by hboon** [comment]
Is it simpler to switch it to 2 separate files for the ellipses button? 1 for each state.

**Comment by eviltofu** [comment]
> Is it simpler to switch it to 2 separate files for the ellipses button? 1 for each state.

But if we change the colours we need to update the files. In my PR, I have tried it the `setTitle` way. If you want to try two files, I'm ok with that too.

**Comment by hboon** [comment]
Yeah, separate image files, easier to stay with the design.

**Comment by eviltofu** [comment]
I just realised, when we start dark/light modes, we would have to use 4 images.

**Comment by eviltofu** [comment]
@hbooon ok done, code now uses pdf image based buttons.
