### ISSUE TITLE
No Receive Option on the USDC Token Page

### ISSUE THREAD

**Issue by Hoanib** [AlphaWallet/alpha-wallet-ios#4119]
Instead of the common option of Receive the USDC info page presents Best Rates and the Send option is on the right instead of the left as on all the others.

![image](https://user-images.githubusercontent.com/100842739/159211440-2739b611-0a1f-4265-9d15-d441c7281db8.png)

**Comment by hboon** [comment]
@Hoanib Are you saying the 2 visible buttons should be Send|Receive like the other native/ERC20 send screens instead of "Best Rates|Send"? If so, this is by design.

* Every token (in this screen), has a list of actions that we can apply to it. The first 2 are displayed more prominently and the rest are chucked into the more/ellipsis button ()
* TokenScript actions ("Best Rates" in this example) are added to the front of the list of actions available

Hence the result. The Receive button is available when we tap the `…` button.

**Comment by Hoanib** [comment]
You are right @HBoon! I failed to realize it.
