### ISSUE TITLE
User shared realm for browser

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4531]
visited links dissapear when change active wallet

**Comment by hboon** [comment]
This is about making history and bookmarks be shared across all wallets, right?

Good one. There's an old issue about this. I can't find it.

Do you think we can do these too?

* Make a migration (for the wallet-specific databases) for history and bookmarks to combine all of them from wallet-specific databases into this new one. I don't know if it will be difficult to sync the migration of all the wallets or affect startup performance
* Give the new database a named ("shared"? instead of Realms default, which is "default")

**Comment by oa-s** [comment]
> This is about making history and bookmarks be shared across all wallets, right?

yes
