### ISSUE TITLE
Is its possible to make properties from XMLHandlers, (Private, Base) as lazy ?

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#4756]
@Boon we got fields `var labelInSingularForm: String? {` that load cp on main thread, every time we reload table view, or when scrolling. as content get loaded from xml file. is there any way to make them computed only once?

**Comment by hboon** [comment]
Hmm. Might be. Do you want me to check and just implement it?

**Comment by oa-s** [comment]
just check

**Comment by oa-s** [comment]
i am thinking about something different. As we got TokenInfo, we can calculate `titleInPluralForm`, `title`, `shortTitleInPluralForm` and other fields from token script file and store them in `TokenInfo`, once token script file has overriden, we can recalculate them again, and rewrite. so we avoid every time calculation, that should help us to speed up the app

**Comment by hboon** [comment]
OK. Avoid unnecessary re-computation makes sense.

2 things:

* are there enough of these to cause a problem for our app? There shouldn't be that much TokenScripts?
* we need to extract the TokenScript engine parts into a separate pod first and make sure caching is not done instead of the pod (we can still cache in the pod, but, but not into `TokenInfo`)
