### ISSUE TITLE
Xcode 13.1 make bootstrap pod build errors

### ISSUE THREAD

**Issue by rectinajh** [AlphaWallet/alpha-wallet-ios#5212]
name: Bug Report
about: Using AlphaWallet iOS , but it's not working as make bootstrap pod build

---

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. git clone git@github.com:AlphaWallet/alpha-wallet-ios.git

2. make bootstrap

**Screenshots**
If applicable, screenshots (preferred to video) to help explain your problem, a wallet address or transaction hash if applicable/possible

<img width="878" alt="image" src="https://user-images.githubusercontent.com/3462559/186394613-88876709-bf16-4e3f-a4af-f0c29327dc35.png">

**Version or build number number**
macOS Monterey 12.5 (21G72)
Apple M1

Xcode :Version 13.3.1 (13E500a)

code version:master branch

git@github.com:AlphaWallet/alpha-wallet-ios.git

**Comment by hboon** [comment]
Can you try this (don't reuse the copy you have) to see if it works?

1. git clone git@github.com:AlphaWallet/alpha-wallet-ios.git
2. cd alpha-wallet-ios
3. Make sure you have ruby 3.0.3 installed along with bundler
4. bundle && bundle exec pod install
5. open AlphaWallet.xcworkspace
6. cmd+B

Otherwise help post the error messages again? Thanks.

**Comment by cryptoaaron** [comment]
This solution works for me, thanks!

**Comment by hboon** [comment]
👍
