### ISSUE TITLE
Alpha Wallet doesn’t connect after OTP code entered and signing on mobile browsers.

### ISSUE THREAD

**Issue by huweihong** [AlphaWallet/alpha-wallet-ios#6345]
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**
Alpha Wallet doesn’t connect after OTP code entered and signing on mobile browsers.

**Steps to reproduce (REQUIRED)**
1. Open [Hotel Bogota Example Dapp](https://tokenscript.github.io/token-negotiator-examples/hotel-bogota-active-negotiation-website/) 
2. Click Book button
3. Click Use token button
4. Enter OTP code and Confirm
5. Click Wallet Connect
6. Click Alpha wallet and connect to wallet
7. Sign in wallet
8. Open browser

**Browser**: Safari, Edge+ios

**App Area**: token negotiator

**Expect**
Redirect page closed and Bogota site opened with payment modal and Pay Now button.

**Observed**
Attestation stuck in redirect page

**Screenshots**
https://user-images.githubusercontent.com/233818/219018783-c093b939-0100-4d49-a179-49cf7523c2ed.mp4

**Version or build number number**
iphone xs max, ios 16.3, AlphaWallet 3.61

**Comment by hboon** [comment]
@huweihong thanks!

**Comment by hboon** [comment]
@oa-s this is the other one.

**Comment by oa-s** [comment]
checking

**Comment by hboon** [comment]
@oa-s can you try to reproduce it with the App Store version? But I’ll do a TestFlight too

**Comment by oa-s** [comment]
i am not quite sure, that it works for me in prod, web page stucks for me, and can't access to the attestation page, tried in safary and web browser as well
https://tokenscript.github.io/token-negotiator-examples/hotel-bogota-passive-negotiation-website/
![IMG_710D8C6578E4-1](https://user-images.githubusercontent.com/96283950/219591016-5d0c4ae8-6013-4368-9506-dcea451bb5e9.jpeg)

**Comment by hboon** [comment]
Oh. Anything we can fix? Is it a bug in AlphaWallet?

**Comment by oa-s** [comment]
in appstore version attestation doesn't work, that is fixed i guess with latest version.

**Comment by hboon** [comment]
Ah ok. Yeah. Thanks.

**Comment by hboon** [comment]
@oa-s if you want me to check, would you help let me know exact steps to reproduce? Couldn't figure it out.

**Comment by oa-s** [comment]
Yes, please

**Comment by hboon** [comment]
Would you help share exact steps to reproduce? I can't figure it out :)

**Comment by oa-s** [comment]
@hboon 

**Steps to reproduce (REQUIRED)**

0. open safari on simulator or real device
1. Go to ticket issuer to create a ticket https://tokenscript.github.io/token-negotiator-examples/ticket-issuer-url-website/
2. Open https://tokenscript.github.io/token-negotiator-examples/hotel-bogota-passive-negotiation-website/
3. Click Book
4. Select Ticket and complete Attestation
5. Click WalletConnect v1
6. Scan QR code and confirm in Alpha wallet
7. Sign eip712 message

**Comment by oa-s** [comment]
let me know if you need some other details

**Comment by hboon** [comment]
I see this after the WalletConnect connection and click the "PAY NOW" button:

<img width="2032" alt="Screenshot 2023-02-23 at 3 40 34 PM" src="https://user-images.githubusercontent.com/56189/220845600-9bb795a1-c388-47ca-98e8-59000c5e8df9.png">

I *thought* I signed the EIP712 message. But I'm not sure.

What do you see when there's an error? 

Tested with macOS Safari + AlphaWallet on device (current TestFlight)

**Comment by oa-s** [comment]
after appearing this popup `Deluxe room`, tap on ticket. to open attestation initialization

**Comment by oa-s** [comment]
you should see something like this

![IMG_6333DD849D6E-1](https://user-images.githubusercontent.com/96283950/220855793-78d4b699-31b4-440f-8172-4bd392291a17.jpeg)

**Comment by hboon** [comment]
Yes. That works for me. I used macOS Safari

**Comment by hboon** [comment]
Do you have the option that blocks pop up enabled maybe?

**Comment by oa-s** [comment]
not clearly understood, what popup do you mean?

**Comment by hboon** [comment]
![image](https://user-images.githubusercontent.com/56189/220869277-c2315203-22c5-4139-a5e0-248b6cf863db.png)

Near the bottom. There's a similar setting for macOS. Is the site trying to open a new window (pop up)?

**Comment by oa-s** [comment]
Yes, got it enabled too

**Comment by oa-s** [comment]
if i am not mistaking there is an error in this popup, 
<img width="300" alt="Screenshot 2023-02-23 at 12 29 48" src="https://user-images.githubusercontent.com/96283950/220881983-1e8669ce-040e-4672-be07-100fc6de9593.png">

it should be reloaded after we sign a message, but when we reload page it reloads all entire window, that cause starting attestation again

**Comment by oa-s** [comment]
because on our side we only sing a message and return response, that all we do.

**Comment by hboon** [comment]
Hi @huweihong,

I tried to reproduce the issue, but I get this on macOS and iOS:

macOS:

<img width="2032" alt="Screenshot 2023-02-23 at 3 40 34 PM" src="https://user-images.githubusercontent.com/56189/220889722-bfb38230-346b-4499-bf15-afeb25c31514.png">

iOS:

<img width="561" alt="Screenshot_2023-02-23_at_13 00 47" src="https://user-images.githubusercontent.com/56189/220889686-57ebd593-d794-4284-af58-d43c7a3afa6a.png">

This is when it's successful right?

Vlad was able to reproduce it earlier. I can sometimes too.

Just to be sure, is the issue where mobile Safari displays this message?

> If you are using AlphaWallet with WalletConnect, please launch the AlphaWallet app

like this:

<img width='200' src='https://user-images.githubusercontent.com/56189/220891460-11b70c2b-3252-47e5-9d33-edde484566ca.jpeg'>

If I manually switch to AlphaWallet app, the signing request did go through:

<img width='200' src='https://user-images.githubusercontent.com/56189/220891731-f781809f-3690-4453-b423-f443f03652a2.PNG'>

I notice that the URL in mobile Safari is this:

https://outlet-stage.brandconnector.io/#evtid=1677150873255&action=get-proof&token=%7B%22devconId%22%3A%226%22%2C%22ticketIdNumber%22%3A1235%2C%22ticketClass%22%3A1%2C%22commitment%22%3A%7B%220%22%3A4%2C%221%22%3A5%2C%222%22%3A186%2C%223%22%3A85%2C%224%22%3A76%2C%225%22%3A46%2C%226%22%3A91%2C%227%22%3A233%2C%228%22%3A224%2C%229%22%3A120%2C%2210%22%3A97%2C%2211%22%3A26%2C%2212%22%3A98%2C%2213%22%3A71%2C%2214%22%3A80%2C%2215%22%3A79%2C%2216%22%3A167%2C%2217%22%3A76%2C%2218%22%3A118%2C%2219%22%3A92%2C%2220%22%3A128%2C%2221%22%3A242%2C%2222%22%3A225%2C%2223%22%3A154%2C%2224%22%3A91%2C%2225%22%3A35%2C%2226%22%3A11%2C%2227%22%3A204%2C%2228%22%3A117%2C%2229%22%3A53%2C%2230%22%3A151%2C%2231%22%3A204%2C%2232%22%3A16%2C%2233%22%3A25%2C%2234%22%3A66%2C%2235%22%3A224%2C%2236%22%3A194%2C%2237%22%3A109%2C%2238%22%3A196%2C%2239%22%3A200%2C%2240%22%3A207%2C%2241%22%3A218%2C%2242%22%3A182%2C%2243%22%3A58%2C%2244%22%3A163%2C%2245%22%3A53%2C%2246%22%3A156%2C%2247%22%3A237%2C%2248%22%3A214%2C%2249%22%3A38%2C%2250%22%3A105%2C%2251%22%3A250%2C%2252%22%3A79%2C%2253%22%3A126%2C%2254%22%3A187%2C%2255%22%3A199%2C%2256%22%3A174%2C%2257%22%3A13%2C%2258%22%3A120%2C%2259%22%3A45%2C%2260%22%3A121%2C%2261%22%3A167%2C%2262%22%3A213%2C%2263%22%3A185%2C%2264%22%3A56%7D%7D&token={%22devconId%22:%226%22,%22ticketIdNumber%22:1235,%22ticketClass%22:1,%22commitment%22:{%220%22:4,%221%22:5,%222%22:186,%223%22:85,%224%22:76,%225%22:46,%226%22:91,%227%22:233,%228%22:224,%229%22:120,%2210%22:97,%2211%22:26,%2212%22:98,%2213%22:71,%2214%22:80,%2215%22:79,%2216%22:167,%2217%22:76,%2218%22:118,%2219%22:92,%2220%22:128,%2221%22:242,%2222%22:225,%2223%22:154,%2224%22:91,%2225%22:35,%2226%22:11,%2227%22:204,%2228%22:117,%2229%22:53,%2230%22:151,%2231%22:204,%2232%22:16,%2233%22:25,%2234%22:66,%2235%22:224,%2236%22:194,%2237%22:109,%2238%22:196,%2239%22:200,%2240%22:207,%2241%22:218,%2242%22:182,%2243%22:58,%2244%22:163,%2245%22:53,%2246%22:156,%2247%22:237,%2248%22:214,%2249%22:38,%2250%22:105,%2251%22:250,%2252%22:79,%2253%22:126,%2254%22:187,%2255%22:199,%2256%22:174,%2257%22:13,%2258%22:120,%2259%22:45,%2260%22:121,%2261%22:167,%2262%22:213,%2263%22:185,%2264%22:56}}

The way WalletConnect works in this case is like this:

Dapp request to sign a message using WC library and:

1. WC library routes the request through their server/WC session
2. AlphaWallet listen to the session and picks up the signing request and display the signing request but it can't switch to the app
3. WC library follows step (1) immediately by visiting in the browser the URL "https://aw.app/wc"
4. iOS sees https://aw.app/wc and knows that AlphaWallet has registered it as a deeplink which it will handle so iOS switches over to iOS app (so the user can see the signing request)

Do you know if we are doing anything special in step (3) which causes it not to work? Because in the screenshot for https://outlet-stage.brandconnector.io/… URL above, it seems like the "https://aw.app/wc" is embedded, I don't think that will let iOS do step (4). But I don't understand why it seems to work sometimes.

Tagging @foxgem as I think he face a similar issue earlier working on this?

**Comment by hboon** [comment]
Refer to https://github.com/AlphaWallet/attestation.id/issues/161
