### ISSUE TITLE
Kitties Cattributes display is missing

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#762]
![5b80ce1f-c82e-42fc-80b8-b280b5ba2040](https://user-images.githubusercontent.com/33795543/46117916-3f950f00-c247-11e8-8699-1bf71816fd9c.jpeg)
![Uploading 2894C3D0-E74A-4333-A80F-6B1A3BD4A9BD.jpeg…]()
![Uploading E99C3D10-DFCD-4B65-BD20-41E7B2D8E839.jpeg…]()

**Comment by farrahfazirah** [comment]
It seems like only certain cattributes have the gem icons. I need to research which cattributes have the gem icon and I'll update on Zeplin.

**Comment by zhangzhongnan928** [comment]
The display should change based on the kitty’s data, or may be we just hide those cat tributes, just keep the picture and introduction. Then make the kitty picture even bigger. 

Regards
Victor

**Comment by zhangzhongnan928** [comment]
how about we hide those cattributes, use the space for bigger picture?
I guess we need to ask some kitty users, whether those cattributes are
important information for them to check every day.

anyone know any serious kitty player?


Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by farrahfazirah** [comment]
> how about we hide those cattributes

I was reading reddit.com/r/cryptokitties and it seems that serious players are more focused on which Gen the kitties are then followed by what cattributes they have.

https://www.reddit.com/r/CryptoKitties/comments/7hjsr7/faq_for_cryptokitties/

I think showing the cattributes is important.

**Comment by farrahfazirah** [comment]
I've updated the Zeplin with the new display for cattributes.

https://zpl.io/V1lgdzQ

<img width="233" alt="screen shot 2018-09-28 at 12 47 27 pm" src="https://user-images.githubusercontent.com/20555752/46188596-b51edf00-c31c-11e8-82fe-9cb23a1ab737.png">

I've included a reference for the jewels. Do note that it isn't an exhaustive list.

@hboon Are you able to fetch the data for which cattributes have which jewels?

**Comment by farrahfazirah** [comment]
> Nope, OpenSea doesn't provide that data.

Ah, in that case we should hide the cattributes then.

@zhangzhongnan928  @hboon Please check Zeplin. I've made the kitty a little bit bigger.

**Comment by hboon** [comment]
@farrahfazirah we can't make the kitties wider (well, maybe just a tiny bit). Some of them have additional decorative elements around them. Refer to the screenshot of the current TestFlight version for an example. I've already stretched the image more or less to the max, it's in fact bleeding out of the display, so that the kitty is almost touching the edge (because there's a lot of white space around the actual graphic downloaded from CryptoKitty).

On the other hand, there's nothing stopping us from chopping off the sides by making it even bigger, actually.. We can scale it up so that we can still see the cat head and body, possible chopping off the tail. Might make a nice visual. Do you want to do a mockup and see if that looks good, for you and Victor? What do you think?

PS: disregard the wrong aspect ratio for the first thumbnail, in the middle of something.

**Comment by zhangzhongnan928** [comment]
Don’t chop, kitty need his tail 😂 and their additional decorative elements. 

Regards
Victor

**Comment by miang719** [comment]
@zhangzhongnan928, is this issue fixed?
