### ISSUE TITLE
Translate CryptoKitty-related strings

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#776]
These 2 lines:

* "transaction.cell.availableButDataUnavailable.title" = "Incomplete Data";

at: https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L159

* "cryptoKitties.cooldown.unknown" = "Unknown";

at: https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L316

**Comment by bootingman** [comment]
@hboon Hi, Boon, I had added the first one, but the second one, I could not get a translation because of lack of context, could you kindly provide a screenshot or  a context?

at: https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L316

**Comment by hboon** [comment]
@bootingman The "Ploddy Cooldown" text can be "Unknown Cooldown" instead. Only localize "Unknown", not "Unknown Cooldown".

![simulator screen shot - iphone x - 2018-10-03 at 13 59 21](https://user-images.githubusercontent.com/56189/46392647-a9fcf200-c714-11e8-9acd-8e2bb84ecac1.png)

**Comment by bootingman** [comment]
thank you Boon, I just add the translation as "未知".

**Comment by hboon** [comment]
@bootingman thanks!
