### ISSUE TITLE
Replace existing parser with a namespace-aware one

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#902]
Ideally supporting XSD validation or at least don't stop us from using another library for validation with it.

**Comment by colourful-land** [comment]
About "supporting XSD validation", I anticipated that you need a test-case for finding a good schema-validation tool.

The attached is a test-case I wrote which uses 2 namespaces in one XML file, since we will need such.

To run the tests, just type "make". It uses 2 validators (xmllint and xerces), both should be available in OS X, just to make a point that the test case files are 100% correct.

    $ make
    xmllint --schema library.xsd book.xml --noout
    book.xml validates
    # the command parameters: https://xerces.apache.org/xerces2-j/samples-sax.html#Counter
    java -classpath /usr/share/java/xercesImpl.jar:/usr/share/java/xmlParserAPIs.jar:/usr/share/java/xercesSamples.jar sax.Counter -n -s book.xml
    book.xml: 23944 ms (11 elems, 4 attrs, 0 spaces, 216 chars)

If your xerces libraries are not installed in the classpath I gave in the `Makefile` that's the part you need to change for OS X.

[validators.tar.gz](https://github.com/AlphaWallet/alpha-wallet-ios/files/2579099/validators.tar.gz)

**Comment by hboon** [comment]
https://github.com/tid-kijyun/Kanna looks good so far for a parser. It wraps libxml2. Haven't found any that incorporates XSD validation. Trying to use libxml2 directly for validation — which probably will not affect the choice of Kanna or any other library for parsing — and see what it's capable of but hitting a snag with Swift C-interop. Researching and looking around in forums. Will circle back.
