### ISSUE TITLE
Mokens 721 contract transfer function failed 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#945]
https://etherscan.io/tx/0x6f19923ad2255d537685af71879ff4a77e9cb068c30949878685c528016f8e4f

https://etherscan.io/tx/0x6c8cf19b9fd98e71c097f722492939211a53dc96d7187984cc47daf9ddabe439

Tried 2 twice
https://mokens.io/moken/121

**Comment by hboon** [comment]
@James-Sangalli it's https://github.com/AlphaWallet/alpha-wallet-ios/issues/830:

CryptoKitties:

    function transfer(address _to, uint256 _tokenId) external; //ultimately calls _transfer()
    function transferFrom(address _from, address _to, uint256 _tokenId) external; //ultimately calls _transfer()
    function _transfer(address _receiver, uint256 _tokenId) internal;

ERC721:

    function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
    function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
    function transferFrom(address _from, address _to, uint256 _tokenId) external payable;

So for ERC721, looks like we should call `safeTransferFrom(address _from, address _to, uint256 _tokenId)` and not `transfer(address _to, uint256 _tokenId)` (also note the missing "From" in the function name), but since CryptoKitties do not implement `safeTransferFrom()`, we'll have to fallback to `transferFrom(address _from, address _to, uint256 _tokenId)` if it `safeTransferFrom()` fails..

PS: EMON/CryptoSaga/ChibiFighters don't implement `safeTransferFrom()` too. I guess they implemented ERC721 fairly early.

**Comment by James-Sangalli** [comment]
@hboon ok, can implement it as default and call the fallback if it fails

**Comment by hboon** [comment]
@James-Sangalli 

These are the ones we know that don't have safeTransferFrom(), but have transfer(address,uint256):

* kitty - 0x06012c8cf97bead5deae237070f9587f8e7a266d 
* CryptoSaga - 0xabc7e6c01237e8eef355bba2bf925a730b714d5f 
* ChibiFighters  - 0x71c118b00759b0851785642541ceb0f4ceea0bd5
